DROP TABLE IF EXISTS citta;

CREATE TABLE citta (
    cit_id INT AUTO_INCREMENT  PRIMARY KEY,
    nome VARCHAR(250) NOT NULL,
    regione VARCHAR(250) NOT NULL
);

INSERT INTO citta (nome, regione) VALUES
('Rome', 'Lazio'),
('Milan', 'Lombardy'),
('Naples', 'Campania'),
('Turin', 'Piedmont'),
('Palermo', 'Sicilia'),
('Genoa', 'Liguria'),
('Bologna', 'Emilia-Romagna'),
('Florence', 'Tuscany'),
('Bari', 'Puglia'),
('Catania', 'Sicilia'),
('Venice', 'Veneto'),
('Verona', 'Veneto'),
('Messina', 'Sicilia'),
('Padova', 'Veneto'),
('Trieste', 'Friuli-Venezia Giulia'),
('Taranto', 'Puglia'),
('Brescia', 'Lombardy'),
('Parma', 'Emilia-Romagna'),
('Prato', 'Tuscany'),
('Modena', 'Emilia-Romagna'),
('Reggio di Calabria', 'Calabria'),
('Reggio Emilia', 'Emilia-Romagna'),
('Perugia', 'Umbria'),
('Ravenna', 'Emilia-Romagna'),
('Livorno', 'Tuscany'),
('Cagliari', 'Sardegna'),
('Foggia', 'Puglia'),
('Rimini', 'Emilia-Romagna'),
('Salerno', 'Campania'),
('Ferrara', 'Emilia-Romagna'),
('Latina', 'Lazio'),
('Giugliano in Campania', 'Campania'),
('Monza', 'Lombardy'),
('Siracusa', 'Sicilia'),
('Bergamo', 'Lombardy'),
('Pescara', 'Abruzzo'),
('Trento', 'Trentino-Alto Adige'),
('Forlì', 'Emilia-Romagna'),
('Sassari', 'Sardegna'),
('Vicenza', 'Veneto'),
('Terni', 'Umbria'),
('Bolzano', 'Trentino-Alto Adige'),
('Novara', 'Piedmont'),
('Piacenza', 'Emilia-Romagna'),
('Ancona', 'Marche'),
('Andria', 'Puglia'),
('Udine', 'Friuli-Venezia Giulia'),
('Arezzo', 'Tuscany'),
('Cesena', 'Emilia-Romagna'),
('Lecce', 'Puglia'),
('Pesaro', 'Marche'),
('Barletta', 'Puglia'),
('Alessandria', 'Piedmont'),
('La Spezia', 'Liguria'),
('Pistoia', 'Tuscany'),
('Pisa', 'Tuscany'),
('Catanzaro', 'Calabria'),
('Mestre', 'Veneto'),
('Lucca', 'Tuscany'),
('Brindisi', 'Puglia'),
('Torre del Greco', 'Campania'),
('Treviso', 'Veneto'),
('Busto Arsizio', 'Lombardy'),
('Como', 'Lombardy'),
('Marsala', 'Sicilia'),
('Grosseto', 'Tuscany'),
('Sesto San Giovanni', 'Lombardy'),
('Pozzuoli', 'Campania'),
('Varese', 'Lombardy'),
('Fiumicino', 'Lazio'),
('Casoria', 'Campania'),
('Asti', 'Piedmont'),
('Cinisello Balsamo', 'Lombardy'),
('Caserta', 'Campania'),
('Gela', 'Sicilia'),
('Ragusa', 'Sicilia'),
('Pavia', 'Lombardy'),
('Cremona', 'Lombardy'),
('Carpi', 'Emilia-Romagna'),
('Quartu Sant’Elena', 'Sardegna'),
('Altamura', 'Puglia'),
('Imola', 'Emilia-Romagna'),
('L’Aquila', 'Abruzzo'),
('Massa', 'Tuscany'),
('Trapani', 'Sicilia'),
('Viterbo', 'Lazio'),
('Cosenza', 'Calabria'),
('Potenza', 'Basilicata'),
('Castellammare di Stabia', 'Campania'),
('Afragola', 'Campania'),
('Vittoria', 'Sicilia'),
('Crotone', 'Calabria'),
('Pomezia', 'Lazio'),
('Vigevano', 'Lombardy'),
('Carrara', 'Tuscany'),
('Caltanissetta', 'Sicilia'),
('Viareggio', 'Tuscany'),
('Benevento', 'Campania'),
('Fano', 'Marche'),
('Savona', 'Liguria'),
('Matera', 'Basilicata'),
('Olbia', 'Sardegna'),
('Legnano', 'Lombardy'),
('Acerra', 'Campania'),
('Marano di Napoli', 'Campania'),
('Molfetta', 'Puglia'),
('Agrigento', 'Sicilia'),
('Faenza', 'Emilia-Romagna'),
('Cerignola', 'Puglia'),
('Moncalieri', 'Piedmont'),
('Foligno', 'Umbria'),
('Manfredonia', 'Puglia'),
('Tivoli', 'Lazio'),
('Cuneo', 'Piedmont'),
('Trani', 'Puglia'),
('Bisceglie', 'Puglia'),
('Bitonto', 'Puglia'),
('Bagheria', 'Sicilia'),
('Portici', 'Campania'),
('Modica', 'Sicilia'),
('San Remo', 'Liguria'),
('Teramo', 'Abruzzo'),
('Montesilvano', 'Abruzzo'),
('Avellino', 'Campania'),
('Siena', 'Tuscany'),
('Gallarate', 'Lombardy'),
('Velletri', 'Lazio'),
('Cava de’ Tirreni', 'Campania'),
('San Severo', 'Puglia'),
('Aversa', 'Campania'),
('Ercolano', 'Campania'),
('Anzio', 'Lazio'),
('Acireale', 'Sicilia'),
('Civitavecchia', 'Lazio'),
('Mazara del Vallo', 'Sicilia'),
('Rovigo', 'Veneto'),
('Pordenone', 'Friuli-Venezia Giulia'),
('Battipaglia', 'Campania'),
('Rho', 'Lombardy'),
('Chieti', 'Abruzzo'),
('Scafati', 'Campania'),
('Scandicci', 'Tuscany'),
('Misterbianco', 'Sicilia'),
('Nettuno', 'Lazio'),
('Ardea', 'Lazio'),
('Collegno', 'Piedmont'),
('Chioggia', 'Veneto'),
('Mantova', 'Lombardy'),
('Campobasso', 'Molise'),
('Casalnuovo di Napoli', 'Campania'),
('Sesto Fiorentino', 'Tuscany'),
('Monopoli', 'Puglia'),
('Martina Franca', 'Puglia'),
('Ascoli Piceno', 'Marche'),
('Rivoli', 'Piedmont'),
('Empoli', 'Tuscany'),
('Corato', 'Puglia'),
('Lecco', 'Lombardy'),
('Paterno', 'Sicilia'),
('Nichelino', 'Piedmont'),
('Cologno Monzese', 'Lombardy'),
('Rieti', 'Lazio'),
('San Benedetto del Tronto', 'Marche'),
('Settimo Torinese', 'Piedmont'),
('Paderno Dugnano', 'Lombardy'),
('Campi Bisenzio', 'Tuscany'),
('Terracina', 'Lazio'),
('Vercelli', 'Piedmont'),
('Capannori', 'Tuscany'),
('Frosinone', 'Lazio'),
('Nocera Inferiore', 'Campania'),
('Lissone', 'Lombardy'),
('Alcamo', 'Sicilia'),
('Lodi', 'Lombardy'),
('Cascina', 'Tuscany'),
('Seregno', 'Lombardy'),
('San Giorgio a Cremano', 'Campania'),
('Senigallia', 'Marche'),
('Marino', 'Lazio'),
('Biella', 'Piedmont'),
('Alghero', 'Sardegna'),
('Gravina in Puglia', 'Puglia'),
('Bassano del Grappa', 'Veneto'),
('Rozzano', 'Lombardy'),
('Torre Annunziata', 'Campania'),
('Civitanova Marche', 'Marche'),
('Imperia', 'Liguria'),
('Avezzano', 'Abruzzo'),
('Desio', 'Lombardy'),
('San Donà di Piave', 'Veneto'),
('Macerata', 'Marche'),
('Ladispoli', 'Lazio'),
('Barcellona-Pozzo di Gotto', 'Sicilia'),
('Albano Laziale', 'Lazio'),
('Monterotondo', 'Lazio'),
('Sassuolo', 'Emilia-Romagna'),
('Sciacca', 'Sicilia'),
('Merano', 'Trentino-Alto Adige'),
('Corigliano Calabro', 'Calabria'),
('Iesi', 'Marche'),
('Eboli', 'Campania'),
('Cantù', 'Lombardy'),
('Rovereto', 'Trentino-Alto Adige'),
('Pomigliano d’Arco', 'Campania'),
('Marcianise', 'Campania'),
('Fondi', 'Lazio'),
('Fasano', 'Puglia'),
('Città di Castello', 'Umbria'),
('Saronno', 'Lombardy'),
('Voghera', 'Lombardy'),
('Schio', 'Veneto'),
('Monreale', 'Sicilia'),
('Maddaloni', 'Campania'),
('Carini', 'Sicilia'),
('Ciampino', 'Lazio'),
('Cesano Maderno', 'Lombardy'),
('Mira', 'Veneto'),
('Modugno', 'Puglia'),
('San Giuliano Milanese', 'Lombardy'),
('Caltagirone', 'Sicilia'),
('Formia', 'Lazio'),
('Cerveteri', 'Lazio'),
('Spoleto', 'Umbria'),
('Melito di Napoli', 'Campania'),
('Caivano', 'Campania'),
('Grugliasco', 'Piedmont'),
('Fermo', 'Marche'),
('Licata', 'Sicilia'),
('Cisterna di Latina', 'Lazio'),
('Chieri', 'Piedmont'),
('Pioltello', 'Lombardy'),
('Rossano', 'Calabria'),
('Nuoro', 'Sardegna'),
('Cassino', 'Lazio'),
('Bollate', 'Lombardy'),
('Casalecchio di Reno', 'Emilia-Romagna'),
('Francavilla Fontana', 'Puglia'),
('Pinerolo', 'Piedmont'),
('Augusta', 'Sicilia'),
('Rende', 'Calabria'),
('Canicattì', 'Sicilia'),
('Belluno', 'Veneto'),
('Adrano', 'Sicilia'),
('Cento', 'Emilia-Romagna'),
('Segrate', 'Lombardy'),
('Limbiate', 'Lombardy'),
('Conegliano', 'Veneto'),
('Osimo', 'Marche'),
('Riccione Marina', 'Emilia-Romagna'),
('Lanciano', 'Abruzzo'),
('Mugnano di Napoli', 'Campania'),
('Somma Vesuviana', 'Campania'),
('Brugherio', 'Lombardy'),
('Corsico', 'Lombardy'),
('Gorizia', 'Friuli-Venezia Giulia'),
('Formigine', 'Emilia-Romagna'),
('Cernusco sul Naviglio', 'Lombardy'),
('Crema', 'Lombardy'),
('Arzano', 'Campania'),
('Angri', 'Campania'),
('Aosta', 'Valle d’Aosta'),
('Casale Monferrato', 'Piedmont'),
('Sant’Antimo', 'Campania'),
('Piombino', 'Tuscany'),
('Vibo Valentia', 'Calabria'),
('Termoli', 'Molise'),
('Venaria Reale', 'Piedmont'),
('Castelfranco Veneto', 'Veneto'),
('Villafranca di Verona', 'Veneto'),
('Lucera', 'Puglia'),
('Castelfranco Emilia', 'Emilia-Romagna'),
('Santa Maria Capua Vetere', 'Campania'),
('Massafra', 'Puglia'),
('Abbiategrasso', 'Lombardy'),
('San Donato Milanese', 'Lombardy'),
('San Lazzaro di Savena', 'Emilia-Romagna'),
('Camaiore', 'Tuscany'),
('Favara', 'Sicilia'),
('Mascalucia', 'Sicilia'),
('Grottaglie', 'Puglia'),
('Frattamaggiore', 'Campania'),
('Partinico', 'Sicilia'),
('Gubbio', 'Umbria'),
('Oristano', 'Sardegna'),
('Sarno', 'Campania'),
('San Giuseppe Vesuviano', 'Campania'),
('Castelvetrano', 'Sicilia'),
('Alba', 'Piedmont'),
('San Giuliano Terme', 'Tuscany'),
('Nardò', 'Puglia'),
('Avola', 'Sicilia'),
('Montebelluna', 'Veneto'),
('Milazzo', 'Sicilia'),
('Villaricca', 'Campania'),
('Ostuni', 'Puglia'),
('Manduria', 'Puglia'),
('Rosignano Marittimo', 'Tuscany'),
('Fabriano', 'Marche'),
('Verbania', 'Piedmont'),
('Marigliano', 'Campania'),
('Canosa di Puglia', 'Puglia'),
('Comiso', 'Sicilia'),
('Treviglio', 'Lombardy'),
('Rapallo', 'Liguria'),
('Bra', 'Piedmont'),
('Aci Catena', 'Sicilia'),
('Misilmeri', 'Sicilia'),
('Pontedera', 'Tuscany'),
('Poggibonsi', 'Tuscany'),
('Selargius', 'Sardegna'),
('Desenzano del Garda', 'Lombardy'),
('Carmagnola', 'Piedmont'),
('Gragnano', 'Campania'),
('Mondragone', 'Campania'),
('Alatri', 'Lazio'),
('Cervia', 'Emilia-Romagna'),
('Vittorio Veneto', 'Veneto'),
('Assisi', 'Umbria'),
('Carbonia', 'Sardegna'),
('Novi Ligure', 'Piedmont'),
('San Giovanni in Persiceto', 'Emilia-Romagna'),
('Belpasso', 'Sicilia'),
('Cecina', 'Tuscany'),
('San Miniato', 'Tuscany'),
('Boscoreale', 'Campania'),
('Spinea', 'Veneto'),
('Mogliano Veneto', 'Veneto'),
('Parabiago', 'Lombardy'),
('Sant’Anastasia', 'Campania'),
('Erice', 'Sicilia'),
('Gioia del Colle', 'Puglia'),
('Giarre', 'Sicilia'),
('Chiavari', 'Liguria'),
('Tortona', 'Piedmont'),
('Enna', 'Sicilia'),
('Triggiano', 'Puglia'),
('San Giovanni Rotondo', 'Puglia'),
('Mirano', 'Veneto'),
('Garbagnate Milanese', 'Lombardy'),
('Terlizzi', 'Puglia'),
('Scicli', 'Sicilia'),
('Niscemi', 'Sicilia'),
('Assèmini', 'Sardegna'),
('Fidenza', 'Emilia-Romagna'),
('Galatina', 'Puglia'),
('Mesagne', 'Puglia'),
('Iglesias', 'Sardegna'),
('Chivasso', 'Piedmont'),
('Putignano', 'Puglia'),
('Santeramo in Colle', 'Puglia'),
('Quarrata', 'Tuscany'),
('Bacoli', 'Campania'),
('Porto Sant’Elpidio', 'Marche'),
('Noicattaro', 'Puglia'),
('Bresso', 'Lombardy'),
('Pontecagnano', 'Campania'),
('Iesolo', 'Veneto'),
('Conversano', 'Puglia'),
('Vimercate', 'Lombardy'),
('Albignasego', 'Veneto'),
('Falconara Marittima', 'Marche'),
('Termini Imerese', 'Sicilia'),
('Valdagno', 'Veneto'),
('Sora', 'Lazio'),
('Cesenatico', 'Emilia-Romagna'),
('Giussano', 'Lombardy'),
('Castel Volturno', 'Campania'),
('Lainate', 'Lombardy'),
('Scandiano', 'Emilia-Romagna'),
('Qualiano', 'Campania'),
('Montichiari', 'Lombardy'),
('Correggio', 'Emilia-Romagna'),
('Francavilla al Mare', 'Abruzzo'),
('Arzignano', 'Veneto'),
('Roseto degli Abruzzi', 'Abruzzo'),
('Bagno a Ripoli', 'Tuscany'),
('Mola di Bari', 'Puglia'),
('Seriate', 'Lombardy'),
('San Giovanni Lupatoto', 'Veneto'),
('Ruvo di Puglia', 'Puglia'),
('Vignola', 'Emilia-Romagna'),
('Legnago', 'Veneto'),
('Pompei', 'Campania'),
('Portogruaro', 'Veneto'),
('Mariano Comense', 'Lombardy'),
('Sezze', 'Lazio'),
('Montevarchi', 'Tuscany'),
('Fossano', 'Piedmont'),
('Nocera Superiore', 'Campania'),
('Thiene', 'Veneto'),
('Sulmona', 'Abruzzo'),
('Copertino', 'Puglia'),
('Ventimiglia', 'Liguria'),
('Albenga', 'Liguria'),
('Noto', 'Sicilia'),
('Biancavilla', 'Sicilia'),
('Magenta', 'Lombardy'),
('Genzano di Roma', 'Lazio'),
('Giulianova', 'Abruzzo'),
('Ottaviano', 'Campania'),
('Pietrasanta', 'Tuscany'),
('Mirandola', 'Emilia-Romagna'),
('Capoterra', 'Sardegna'),
('Muggiò', 'Lombardy'),
('Castiglione delle Stiviere', 'Lombardy'),
('Lentini', 'Sicilia'),
('Dalmine', 'Lombardy'),
('Meda', 'Lombardy'),
('Seveso', 'Lombardy'),
('Ivrea', 'Piedmont'),
('San Giovanni la Punta', 'Sicilia'),
('Ceccano', 'Lazio'),
('Orbassano', 'Piedmont'),
('Nova Milanese', 'Lombardy'),
('Montecchio Maggiore', 'Veneto'),
('Fucecchio', 'Tuscany'),
('Mentana', 'Lazio'),
('Ortona', 'Abruzzo'),
('Vigonza', 'Veneto'),
('Selvazzano Dentro', 'Veneto'),
('Floridia', 'Sicilia'),
('Palma di Montechiaro', 'Sicilia'),
('Cardito', 'Campania'),
('San Cataldo', 'Sicilia'),
('Frascati', 'Lazio'),
('Ariano Irpino', 'Campania'),
('Mondovì', 'Piedmont'),
('Massarosa', 'Tuscany'),
('Ginosa', 'Puglia'),
('Porto Torres', 'Sardegna'),
('Mercato San Severino', 'Campania'),
('Pachino', 'Sicilia'),
('Comacchio', 'Emilia-Romagna'),
('Sant’Arcangelo di Romagna', 'Emilia-Romagna'),
('Sarzana', 'Liguria'),
('Cortona', 'Tuscany'),
('Castrovillari', 'Calabria'),
('Bressanone', 'Trentino-Alto Adige'),
('Poggiomarino', 'Campania'),
('Paese', 'Veneto'),
('Agropoli', 'Campania'),
('Palestrina', 'Lazio'),
('Piazza Armerina', 'Sicilia'),
('Borgomanero', 'Piedmont'),
('Isernia', 'Molise'),
('Colle di Val d’Elsa', 'Tuscany'),
('Sondrio', 'Lombardy'),
('Savigliano', 'Piedmont'),
('Argenta', 'Emilia-Romagna'),
('Martellago', 'Veneto'),
('Senago', 'Lombardy'),
('Palo del Colle', 'Puglia'),
('Casal di Principe', 'Campania'),
('Corciano', 'Umbria'),
('Anagni', 'Lazio'),
('San Bonifacio', 'Veneto'),
('Colleferro', 'Lazio'),
('Pergine Valsugana', 'Trentino-Alto Adige'),
('Follonica', 'Tuscany'),
('Sessa Aurunca', 'Campania'),
('Rosolini', 'Sicilia'),
('Recanati', 'Marche'),
('Suzzara', 'Lombardy'),
('Monsummano', 'Tuscany'),
('Ferentino', 'Lazio'),
('Sestu', 'Sardegna'),
('Trezzano sul Naviglio', 'Lombardy'),
('Vico Equense', 'Campania'),
('Castel San Pietro Terme', 'Emilia-Romagna'),
('Feltre', 'Veneto'),
('Pontassieve', 'Tuscany'),
('Acquaviva delle Fonti', 'Puglia'),
('Trecate', 'Piedmont'),
('Gallipoli', 'Puglia'),
('Gaeta', 'Lazio'),
('Montecatini Terme', 'Tuscany'),
('Sabaudia', 'Lazio'),
('Cornaredo', 'Lombardy'),
('Gorgonzola', 'Lombardy'),
('Romano di Lombardia', 'Lombardy'),
('Oderzo', 'Veneto'),
('Grottaferrata', 'Lazio'),
('Acri', 'Calabria'),
('Veroli', 'Lazio'),
('Giovinazzo', 'Puglia'),
('Lastra a Signa', 'Tuscany'),
('Orvieto', 'Umbria'),
('Montalto Uffugo', 'Calabria'),
('Rivalta di Torino', 'Piedmont'),
('San Salvo', 'Abruzzo'),
('Cittadella', 'Veneto'),
('Bussolengo', 'Veneto'),
('Ischia', 'Campania'),
('Abano Terme', 'Veneto'),
('Gioia Tauro', 'Calabria'),
('Casarano', 'Puglia'),
('Villabate', 'Sicilia'),
('Viadana', 'Lombardy'),
('Pallazzolo sull’Oglio', 'Lombardy'),
('Cormano', 'Lombardy'),
('Novate Milanese', 'Lombardy'),
('Sacile', 'Friuli-Venezia Giulia'),
('Piove di Sacco', 'Veneto'),
('Trentola', 'Campania'),
('Ceglie Messapico', 'Puglia'),
('Minturno', 'Lazio'),
('Casamassima', 'Puglia'),
('Monserrato', 'Sardegna'),
('Salsomaggiore Terme', 'Emilia-Romagna'),
('Sant’Antonio Abate', 'Campania'),
('Acqui Terme', 'Piedmont'),
('Pescia', 'Tuscany'),
('Castellana Grotte', 'Puglia'),
('Pozzallo', 'Sicilia'),
('Adria', 'Veneto'),
('Anguillara Sabazia', 'Lazio'),
('Tolentino', 'Marche'),
('Spoltore', 'Abruzzo'),
('Arese', 'Lombardy'),
('Narni', 'Umbria'),
('Casalgrande', 'Emilia-Romagna'),
('Rovato', 'Lombardy'),
('Bracciano', 'Lazio'),
('Noci', 'Puglia'),
('San Vito dei Normanni', 'Puglia'),
('Cassano d’Adda', 'Lombardy'),
('San Mauro Torinese', 'Piedmont'),
('Bronte', 'Sicilia'),
('Chiari', 'Lombardy'),
('Zola Predosa', 'Emilia-Romagna'),
('Santa Marinella', 'Lazio'),
('Signa', 'Tuscany'),
('Tradate', 'Lombardy'),
('Ariccia', 'Lazio'),
('Scorzè', 'Veneto'),
('Ribera', 'Sicilia'),
('Valenza', 'Piedmont'),
('Cusano Milanino', 'Lombardy'),
('Montemurlo', 'Tuscany'),
('Ghedi', 'Lombardy'),
('Marsciano', 'Umbria'),
('Ciriè', 'Piedmont'),
('Palmi', 'Calabria'),
('Castelfidardo', 'Marche'),
('Rutigliano', 'Puglia'),
('Terzigno', 'Campania'),
('Aci Castello', 'Sicilia'),
('Melzo', 'Lombardy'),
('Budrio', 'Emilia-Romagna'),
('Borgo San Lorenzo', 'Tuscany'),
('Castel Maggiore', 'Emilia-Romagna'),
('Sestri Levante', 'Liguria'),
('Piossasco', 'Piedmont'),
('Corbetta', 'Lombardy'),
('Capua', 'Campania'),
('Cassano al Ionio', 'Calabria'),
('Domodossola', 'Piedmont'),
('Siderno Marina', 'Calabria'),
('Palma Campania', 'Campania'),
('Cordenons', 'Friuli-Venezia Giulia'),
('Melegnano', 'Lombardy'),
('Aci Sant’Antonio', 'Sicilia'),
('Valguarnera Caropepe', 'Sicilia'),
('Polignano a Mare', 'Puglia'),
('Cercola', 'Campania'),
('Laives', 'Trentino-Alto Adige'),
('Carate Brianza', 'Lombardy'),
('Valenzano', 'Puglia'),
('Grumo Nevano', 'Campania'),
('Zagarolo', 'Lazio'),
('Somma Lombardo', 'Lombardy'),
('Arcore', 'Lombardy'),
('Calenzano', 'Tuscany'),
('Albino', 'Lombardy'),
('Villorba', 'Veneto'),
('Melfi', 'Basilicata'),
('Beinasco', 'Piedmont'),
('Forio', 'Campania'),
('Isola Capo Rizzuto', 'Calabria'),
('Agliana', 'Tuscany'),
('Santa Maria di Sala', 'Veneto'),
('Savignano sul Rubicone', 'Emilia-Romagna'),
('Carlentini', 'Sicilia'),
('Arco', 'Trentino-Alto Adige'),
('Sona', 'Veneto'),
('Policoro', 'Basilicata'),
('Orta Nova', 'Puglia'),
('Pisticci', 'Basilicata'),
('Maranello', 'Emilia-Romagna'),
('Monselice', 'Veneto'),
('Sìnnai', 'Sardegna'),
('Tricase', 'Puglia'),
('Pianoro', 'Emilia-Romagna'),
('Marcon', 'Veneto'),
('Pavullo nel Frignano', 'Emilia-Romagna'),
('Bareggio', 'Lombardy'),
('Castelfiorentino', 'Tuscany'),
('Pescantina', 'Veneto'),
('Rocca di Papa', 'Lazio'),
('Cattolica', 'Emilia-Romagna'),
('Nerviano', 'Lombardy'),
('San Casciano in Val di Pesa', 'Tuscany'),
('Campagna', 'Campania'),
('Sant’Elpidio a Mare', 'Marche'),
('Carovigno', 'Puglia'),
('Fiorano Modenese', 'Emilia-Romagna'),
('Negrar', 'Veneto'),
('Torre Maggiore', 'Puglia'),
('Castellaneta', 'Puglia'),
('San Giovanni in Fiore', 'Calabria'),
('Baronissi', 'Campania'),
('Vimodrone', 'Lombardy'),
('Adelfia', 'Puglia'),
('Saluzzo', 'Piedmont'),
('Preganziol', 'Veneto'),
('Bovisio Masciago', 'Lombardy'),
('Scordia', 'Sicilia'),
('San Giovanni Valdarno', 'Tuscany'),
('Alpignano', 'Piedmont'),
('Malnate', 'Lombardy'),
('Vedelago', 'Veneto'),
('Bagnacavallo', 'Emilia-Romagna'),
('Medicina', 'Emilia-Romagna'),
('Giaveno', 'Piedmont'),
('Porto Empedocle', 'Sicilia'),
('Colle Salvetti', 'Tuscany'),
('Gussago', 'Lombardy'),
('Palagonia', 'Sicilia'),
('Monesiglio', 'Piedmont'),
('Todi', 'Umbria'),
('Brunico', 'Trentino-Alto Adige'),
('Reggello', 'Tuscany'),
('Umbertide', 'Umbria'),
('Cerea', 'Veneto'),
('Lonigo', 'Veneto'),
('Rubano', 'Veneto'),
('Sorrento', 'Campania'),
('Leinì', 'Piedmont'),
('Brusciano', 'Campania'),
('Este', 'Veneto'),
('Ispica', 'Sicilia'),
('Copparo', 'Emilia-Romagna'),
('Tarquinia', 'Lazio'),
('Civita Castellana', 'Lazio'),
('Caravaggio', 'Lombardy'),
('Saviano', 'Campania'),
('Cadoneghe', 'Veneto'),
('Grottammare', 'Marche'),
('Codroipo', 'Friuli-Venezia Giulia'),
('Frattaminore', 'Campania'),
('Palagiano', 'Puglia'),
('Bovolone', 'Veneto'),
('Sava', 'Puglia'),
('Valmontone', 'Lazio'),
('Porto San Giorgio', 'Marche'),
('Certaldo', 'Tuscany'),
('Samarate', 'Lombardy'),
('Noale', 'Veneto'),
('Martinsicuro', 'Abruzzo'),
('Nonantola', 'Emilia-Romagna'),
('Codogno', 'Lombardy'),
('Lentate sul Seveso', 'Lombardy'),
('Sansepolcro', 'Tuscany'),
('Mottola', 'Puglia'),
('Potenza Picena', 'Marche'),
('Azzano Decimo', 'Friuli-Venezia Giulia'),
('Paola', 'Calabria'),
('Silvi Paese', 'Abruzzo'),
('Fiano Romano', 'Lazio'),
('Galliate', 'Piedmont'),
('Capurso', 'Puglia'),
('Concorezzo', 'Lombardy'),
('Molinella', 'Emilia-Romagna'),
('Finale Emilia', 'Emilia-Romagna'),
('Besana in Brianza', 'Lombardy'),
('Altopascio', 'Tuscany'),
('San Cesareo', 'Lazio'),
('Galatone', 'Puglia'),
('Agrate Brianza', 'Lombardy'),
('Ponsacco', 'Tuscany'),
('Taurianova', 'Calabria'),
('Carugate', 'Lombardy'),
('San Martino Buon Albergo', 'Veneto'),
('Castiglione del Lago', 'Umbria'),
('Volpiano', 'Piedmont'),
('Casalmaggiore', 'Lombardy'),
('Valeggio sul Mincio', 'Veneto'),
('Castenaso', 'Emilia-Romagna'),
('Mortara', 'Lombardy'),
('Corridonia', 'Marche'),
('Castellarano', 'Emilia-Romagna'),
('Pianezza', 'Piedmont'),
('Soliera', 'Emilia-Romagna'),
('Omegna', 'Piedmont'),
('Casalpusterlengo', 'Lombardy'),
('Fiorenzuola d’Arda', 'Emilia-Romagna'),
('Sannicandro Garganico', 'Puglia'),
('Cerro Maggiore', 'Lombardy'),
('Castellammare del Golfo', 'Sicilia'),
('Laterza', 'Puglia'),
('Surbo', 'Puglia'),
('San Giorgio Ionico', 'Puglia'),
('San Vito al Tagliamento', 'Friuli-Venezia Giulia'),
('Zevio', 'Veneto'),
('Castelnuovo Rangone', 'Emilia-Romagna'),
('Città Sant’Angelo', 'Abruzzo'),
('Guastalla', 'Emilia-Romagna'),
('Dolo', 'Veneto'),
('Gualdo Tadino', 'Umbria'),
('Pineto', 'Abruzzo'),
('Pontinia', 'Lazio'),
('Sasso Marconi', 'Emilia-Romagna'),
('Merate', 'Lombardy'),
('Malo', 'Veneto'),
('Rubiera', 'Emilia-Romagna'),
('Sorso', 'Sardegna'),
('Magione', 'Umbria'),
('Sommacampagna', 'Veneto'),
('Cirò Marina', 'Calabria'),
('Rosarno', 'Calabria'),
('Cassano delle Murge', 'Puglia'),
('Orbetello', 'Tuscany'),
('Chiaravalle', 'Marche'),
('Ospitaletto', 'Lombardy'),
('Campodarsego', 'Veneto'),
('Carmignano', 'Tuscany'),
('Vinci', 'Tuscany'),
('Trinitapoli', 'Puglia'),
('Collecchio', 'Emilia-Romagna'),
('Cossato', 'Piedmont'),
('Santa Croce sull’ Arno', 'Tuscany'),
('Riposto', 'Sicilia'),
('Impruneta', 'Tuscany'),
('Pedara', 'Sicilia'),
('Sant’Arpino', 'Campania'),
('Roncade', 'Veneto'),
('Urbino', 'Marche'),
('Trepuzzi', 'Puglia'),
('Rosà', 'Veneto'),
('Luino', 'Lombardy'),
('Latiano', 'Puglia'),
('Priverno', 'Lazio'),
('Castellanza', 'Lombardy'),
('Leno', 'Lombardy'),
('Mascali', 'Sicilia'),
('Cefalù', 'Sicilia'),
('Taglio', 'Veneto'),
('Massalubrense', 'Campania'),
('Mondolfo', 'Marche'),
('Montelupo Fiorentino', 'Tuscany'),
('Bondeno', 'Emilia-Romagna'),
('Maglie', 'Puglia'),
('Locorotondo', 'Puglia'),
('Rescaldina', 'Lombardy'),
('Solaro', 'Lombardy'),
('Fiesole', 'Tuscany'),
('Leverano', 'Puglia'),
('Oleggio', 'Piedmont'),
('Casandrino', 'Campania'),
('Artena', 'Lazio'),
('Tempio Pausania', 'Sardegna'),
('Marostica', 'Veneto'),
('Squinzano', 'Puglia'),
('Vetralla', 'Lazio'),
('Villacidro', 'Sardegna'),
('Santa Maria a Vico', 'Campania'),
('Taggia', 'Liguria'),
('Montepulciano', 'Tuscany'),
('Amantea', 'Calabria'),
('Villasanta', 'Lombardy'),
('Fisciano', 'Campania'),
('Arona', 'Piedmont'),
('Caselle Torinese', 'Piedmont'),
('Veglie', 'Puglia'),
('Vieste', 'Puglia'),
('Travagliato', 'Lombardy'),
('Monteroni di Lecce', 'Puglia'),
('Fara in Sabina', 'Lazio'),
('Cervignano del Friuli', 'Friuli-Venezia Giulia'),
('Calolziocorte', 'Lombardy'),
('Opera', 'Lombardy'),
('Busto Garolfo', 'Lombardy'),
('Cassina de’ Pecchi', 'Lombardy'),
('San Ferdinando di Puglia', 'Puglia'),
('Statte', 'Puglia'),
('Dueville', 'Veneto'),
('Cavarzere', 'Veneto'),
('Castel San Giorgio', 'Campania'),
('Castel San Giovanni', 'Emilia-Romagna'),
('Arzachena', 'Sardegna'),
('Novellara', 'Emilia-Romagna'),
('Crispiano', 'Puglia'),
('Villa San Giovanni', 'Calabria'),
('Alzano Lombardo', 'Lombardy'),
('Nicosia', 'Sicilia'),
('San Marco in Lamis', 'Puglia'),
('Lanuvio', 'Lazio'),
('Rezzato', 'Lombardy'),
('San Pietro Vernotico', 'Puglia'),
('Melilli', 'Sicilia'),
('Montesarchio', 'Campania'),
('Crevalcore', 'Emilia-Romagna'),
('Montefiascone', 'Lazio'),
('Montespertoli', 'Tuscany'),
('Latisana', 'Friuli-Venezia Giulia'),
('Lariano', 'Lazio'),
('Varedo', 'Lombardy'),
('Lavello', 'Basilicata'),
('Misano Adriatico', 'Emilia-Romagna'),
('Castelfranco di Sotto', 'Tuscany'),
('Sarezzo', 'Lombardy'),
('Capo d’Orlando', 'Sicilia'),
('Forlimpopoli', 'Emilia-Romagna'),
('Grammichele', 'Sicilia'),
('Patti', 'Sicilia'),
('Rionero in Vulture', 'Basilicata'),
('Quartucciu', 'Sardegna'),
('Castiglion Fiorentino', 'Tuscany'),
('Calderara di Reno', 'Emilia-Romagna'),
('Quattro Castella', 'Emilia-Romagna'),
('Sant’Angelo Lodigiano', 'Lombardy'),
('Palombara Sabina', 'Lazio'),
('Apricena', 'Puglia'),
('Cairo Montenotte', 'Liguria'),
('Castelnuovo di Verona', 'Veneto'),
('Pontecorvo', 'Lazio'),
('Camponogara', 'Veneto'),
('Varazze', 'Liguria'),
('Stezzano', 'Lombardy'),
('Múggia', 'Friuli-Venezia Giulia'),
('Manerbio', 'Lombardy'),
('Leonforte', 'Sicilia'),
('San Martino di Lupari', 'Veneto'),
('Ficarazzi', 'Sicilia'),
('Formello', 'Lazio'),
('Santa Maria a Monte', 'Tuscany'),
('Casatenovo', 'Lombardy'),
('Casale sul Sile', 'Veneto'),
('Campiglia Marittima', 'Tuscany'),
('Vigodarzere', 'Veneto'),
('Piano di Sorrento', 'Campania'),
('San Biagio di Callalta', 'Veneto'),
('Seravezza', 'Tuscany'),
('Barrafranca', 'Sicilia'),
('Carpenedolo', 'Lombardy'),
('Noceto', 'Emilia-Romagna'),
('Trebaseleghe', 'Veneto'),
('Salzano', 'Veneto'),
('Cicciano', 'Campania'),
('Calcinato', 'Lombardy'),
('Chiampo', 'Veneto'),
('Montegranaro', 'Marche'),
('Santo Stino di Livenza', 'Veneto'),
('Lipari', 'Sicilia'),
('Tezze sul Brenta', 'Veneto'),
('Cavallino', 'Puglia'),
('Loreto', 'Marche'),
('Spilamberto', 'Emilia-Romagna'),
('Monte di Procida', 'Campania'),
('Grumo Appula', 'Puglia'),
('Monte San Giovanni Campano', 'Lazio'),
('Lauria Inferiore', 'Basilicata'),
('Montecorvino Rovella', 'Campania'),
('Monteprandone', 'Marche'),
('Bagnolo Mella', 'Lombardy'),
('Borgosesia', 'Piedmont'),
('Francofonte', 'Sicilia'),
('Raffadali', 'Sicilia'),
('Figline Valdarno', 'Tuscany'),
('Sala Consilina', 'Campania'),
('Castel Goffredo', 'Lombardy'),
('Lavagna', 'Liguria'),
('Porto Recanati', 'Marche'),
('Avigliana', 'Piedmont'),
('Calcinaia', 'Tuscany'),
('Canegrate', 'Lombardy'),
('Sinalunga', 'Tuscany'),
('Rivarolo Canavese', 'Piedmont'),
('Terrasini Favarotta', 'Sicilia'),
('Fontanafredda', 'Friuli-Venezia Giulia'),
('Fagnano Olona', 'Lombardy'),
('Borgo San Dalmazzo', 'Piedmont'),
('Menfi', 'Sicilia'),
('Solofra', 'Campania'),
('San Severino Marche', 'Marche'),
('Bernalda', 'Basilicata'),
('Olgiate Olona', 'Lombardy'),
('Orzinuovi', 'Lombardy'),
('San Pietro in Casale', 'Emilia-Romagna'),
('Ugento', 'Puglia'),
('Morbegno', 'Lombardy'),
('Sant’Agata di Militello', 'Sicilia'),
('Mercogliano', 'Campania'),
('Locri', 'Calabria'),
('Pianiga', 'Veneto'),
('Monte Sant’Angelo', 'Puglia'),
('San Prisco', 'Campania'),
('Anzola dell’Emilia', 'Emilia-Romagna'),
('Russi', 'Emilia-Romagna'),
('Teano', 'Campania'),
('Gricignano d’Aversa', 'Campania'),
('Terranuova Bracciolini', 'Tuscany'),
('Lana', 'Trentino-Alto Adige'),
('Eraclea', 'Veneto'),
('Cinisi', 'Sicilia'),
('Sedriano', 'Lombardy'),
('Rottofreno', 'Emilia-Romagna'),
('Gavardo', 'Lombardy'),
('Motta Sant’Anastasia', 'Sicilia'),
('Villa Literno', 'Campania'),
('Calvizzano', 'Campania'),
('Bibbiena', 'Tuscany'),
('Biassono', 'Lombardy'),
('Spilimbergo', 'Friuli-Venezia Giulia'),
('Spresiano', 'Veneto'),
('Monte Compatri', 'Lazio'),
('Trezzo sull’Adda', 'Lombardy'),
('Vecchiano', 'Tuscany'),
('Carmiano', 'Puglia'),
('Rocca Priora', 'Lazio'),
('Pieve di Soligo', 'Veneto'),
('Camposampiero', 'Veneto'),
('Granarolo del l’Emilia', 'Emilia-Romagna'),
('Altavilla Vicentina', 'Veneto'),
('Bitetto', 'Puglia'),
('Baranzate', 'Lombardy'),
('Arluno', 'Lombardy'),
('Occhiobello', 'Ferrara'),
('Cornedo Vicentino', 'Veneto'),
('Taviano', 'Puglia'),
('Ronchi dei Legionari', 'Friuli-Venezia Giulia'),
('Portoferraio', 'Tuscany'),
('Alfonsine', 'Emilia-Romagna'),
('Lizzanello', 'Puglia'),
('Monteforte Irpino', 'Campania'),
('Borgaro Torinese', 'Piedmont'),
('San Mauro Pascoli', 'Emilia-Romagna'),
('San Gennaro Vesuviano', 'Campania'),
('Giffoni Valle Piana', 'Campania'),
('Priolo Gargallo', 'Sicilia'),
('San Gregorio di Catania', 'Sicilia'),
('Mazzarino', 'Sicilia'),
('Susegana', 'Veneto'),
('Amelia', 'Umbria'),
('San Michele al Tagliamento', 'Veneto'),
('Sant’Ambrogio di Valpolicella', 'Veneto'),
('Lonate Pozzolo', 'Lombardy'),
('Margherita di Savoia', 'Puglia'),
('Taurisano', 'Puglia'),
('Campobello di Mazara', 'Sicilia'),
('Tortoreto', 'Abruzzo'),
('Maniago', 'Friuli-Venezia Giulia'),
('Codigoro', 'Emilia-Romagna'),
('Venosa', 'Basilicata'),
('Fiume Veneto', 'Friuli-Venezia Giulia'),
('Guspini', 'Sardegna'),
('Lendinara', 'Veneto'),
('Serravalle Pistoiese', 'Tuscany'),
('Torri di Quartesolo', 'Veneto'),
('Casteldaccia', 'Sicilia'),
('Stradella', 'Lombardy'),
('Olgiate Comasco', 'Lombardy'),
('Portomaggiore', 'Emilia-Romagna'),
('Finale Ligure', 'Liguria'),
('Caorle', 'Veneto'),
('Valmadrera', 'Lombardy'),
('Campagnano di Roma', 'Lazio'),
('Cisternino', 'Puglia'),
('Capaci', 'Sicilia'),
('Isola della Scala', 'Veneto'),
('Gardone Val Trompia', 'Lombardy'),
('Siniscola', 'Sardegna'),
('Nembro', 'Lombardy'),
('Pulsano', 'Puglia'),
('Ponte San Pietro', 'Lombardy'),
('Mestrino', 'Veneto'),
('Isola del Liri', 'Lazio'),
('Castenedolo', 'Lombardy'),
('Arenzano', 'Liguria'),
('Ravanusa', 'Sicilia'),
('Musile di Piave', 'Veneto'),
('Montegrotto Terme', 'Veneto'),
('Matino', 'Puglia'),
('Paullo', 'Lombardy'),
('Casièr', 'Veneto'),
('Riesi', 'Sicilia'),
('Cave', 'Lazio'),
('Creazzo', 'Veneto'),
('Ovada', 'Piedmont'),
('Avigliano', 'Basilicata'),
('Zero Branco', 'Veneto'),
('Acate', 'Sicilia'),
('Paceco', 'Sicilia'),
('Castelvetro di Modena', 'Emilia-Romagna'),
('Bitritto', 'Puglia'),
('Caldogno', 'Veneto'),
('Sant’Ilario d’Enza', 'Emilia-Romagna'),
('Camisano Vicentino', 'Veneto'),
('Melito di Porto Salvo', 'Calabria'),
('Belmonte Mezzagno', 'Sicilia'),
('La Maddalena', 'Sardegna'),
('Castano Primo', 'Lombardy'),
('Loano', 'Liguria'),
('San Giustino', 'Umbria'),
('Santa Flavia', 'Sicilia'),
('Venafro', 'Molise'),
('Piazzola sul Brenta', 'Veneto'),
('Carbonera', 'Veneto'),
('Cologno al Serio', 'Lombardy'),
('Cividale del Friuli', 'Friuli-Venezia Giulia'),
('Sant’Antìoco', 'Sardegna'),
('Sant’Agata de’ Goti', 'Campania'),
('Montopoli in Val d’Arno', 'Tuscany'),
('Sesto Calende', 'Lombardy'),
('Cerese', 'Lombardy'),
('Corleone', 'Sicilia'),
('Pellezzano', 'Campania'),
('Aulla', 'Tuscany'),
('Tortolì', 'Sardegna'),
('Trecastagni', 'Sicilia'),
('Scalea', 'Calabria'),
('Cepagatti', 'Abruzzo'),
('Racale', 'Puglia'),
('Castel Mella', 'Lombardy'),
('Cerreto Guidi', 'Tuscany'),
('Montechiarugolo', 'Emilia-Romagna'),
('Atripalda', 'Campania'),
('Monte San Pietro', 'Emilia-Romagna'),
('Santa Croce Camerina', 'Sicilia'),
('Inzago', 'Lombardy'),
('Bertinoro', 'Emilia-Romagna'),
('San Valentino Torio', 'Campania'),
('Cazzago San Martino', 'Lombardy'),
('Barberino di Mugello', 'Tuscany'),
('Cameri', 'Piedmont'),
('Trofarello', 'Piedmont'),
('Cori', 'Lazio'),
('Celano', 'Abruzzo'),
('Taormina', 'Sicilia'),
('Gemona del Friuli', 'Friuli-Venezia Giulia'),
('Ramacca', 'Sicilia'),
('Botticino Sera', 'Lombardy'),
('Medesano', 'Emilia-Romagna'),
('Grezzana', 'Veneto'),
('San Felice sul Panaro', 'Emilia-Romagna'),
('Motta di Livenza', 'Veneto'),
('Capena', 'Lazio'),
('Alassio', 'Liguria'),
('Montale', 'Tuscany'),
('Randazzo', 'Sicilia'),
('Itri', 'Lazio'),
('Trevignano', 'Veneto'),
('Alberobello', 'Puglia'),
('Cornate d’Adda', 'Lombardy'),
('Gambettola', 'Emilia-Romagna'),
('Cadelbosco di Sopra', 'Emilia-Romagna'),
('Campolongo Maggiore', 'Veneto'),
('Salemi', 'Sicilia'),
('Massa Lombarda', 'Emilia-Romagna'),
('Salò', 'Lombardy'),
('Peschiera del Garda', 'Veneto'),
('Atessa', 'Abruzzo'),
('Montecchio Emilia', 'Emilia-Romagna'),
('Poirino', 'Piedmont'),
('Ozieri', 'Sardegna'),
('Martinengo', 'Lombardy'),
('Mussomeli', 'Sicilia'),
('Coriano', 'Emilia-Romagna'),
('Fiuggi', 'Lazio'),
('Torre Santa Susanna', 'Puglia'),
('Macerata Campania', 'Campania'),
('San Marzano sul Sarno', 'Campania'),
('Castelnovo ne’ Monti', 'Emilia-Romagna'),
('Procida', 'Campania'),
('Cutro', 'Calabria'),
('Castelli Calepio', 'Lombardy'),
('Canelli', 'Piedmont'),
('Trabia', 'Sicilia'),
('Partanna', 'Sicilia'),
('Bordighera', 'Liguria'),
('Cislago', 'Lombardy'),
('Polistena', 'Calabria'),
('Concordia Sagittaria', 'Veneto'),
('Valdobbiadene', 'Veneto'),
('Badia Polesine', 'Veneto'),
('Langhirano', 'Emilia-Romagna'),
('Rignano Flaminio', 'Lazio'),
('Campi Salentina', 'Puglia'),
('Nizza Monferrato', 'Piedmont'),
('Mandello del Lario', 'Lombardy'),
('San Maurizio Canavese', 'Piedmont'),
('Montignoso', 'Tuscany'),
('Usmate Velate', 'Lombardy'),
('Volterra', 'Tuscany'),
('Cittanova', 'Calabria'),
('Induno Olona', 'Lombardy'),
('Boscotrecase', 'Campania'),
('Isola Vicentina', 'Veneto'),
('Bibbiano', 'Emilia-Romagna'),
('Conselve', 'Veneto'),
('Goito', 'Lombardy'),
('Altofonte', 'Sicilia'),
('Locate di Triulzi', 'Lombardy'),
('Volpago del Montello', 'Veneto'),
('Terralba', 'Sardegna'),
('Bomporto', 'Emilia-Romagna'),
('Silea', 'Veneto'),
('Vigasio', 'Veneto'),
('Capodrise', 'Campania'),
('Lerici', 'Liguria'),
('Bisignano', 'Calabria'),
('Bagnara Calabra', 'Calabria'),
('Sedico', 'Veneto'),
('Cingoli', 'Marche'),
('Busca', 'Piedmont'),
('Novi di Modena', 'Emilia-Romagna'),
('Bucine', 'Tuscany'),
('Sermoneta', 'Lazio'),
('Asola', 'Lombardy'),
('Vaiano', 'Tuscany'),
('San Giorgio del Sannio', 'Campania'),
('Sovicille', 'Tuscany'),
('Morrovalle', 'Marche'),
('San Felice Circeo', 'Lazio'),
('Tolmezzo', 'Friuli-Venezia Giulia'),
('Poggio a Caiano', 'Tuscany'),
('Cetraro', 'Calabria'),
('Bonate di Sopra', 'Lombardy'),
('Macomer', 'Sardegna'),
('Oppeano', 'Veneto'),
('Verucchio', 'Emilia-Romagna'),
('Barano d’Ischia', 'Campania'),
('Melendugno', 'Puglia'),
('Vigonovo', 'Veneto'),
('Lizzano', 'Puglia'),
('Meldola', 'Emilia-Romagna'),
('Castelletto sopra Ticino', 'Piedmont'),
('San Vendemiano', 'Veneto'),
('Racconigi', 'Piedmont'),
('Castellamonte', 'Piedmont'),
('Monteriggioni', 'Tuscany'),
('Lomazzo', 'Lombardy'),
('Cavriago', 'Emilia-Romagna'),
('Gambolò', 'Lombardy'),
('Quinto di Treviso', 'Veneto'),
('Urgnano', 'Lombardy'),
('Sannicandro di Bari', 'Puglia'),
('Barga', 'Tuscany'),
('Casaluce', 'Campania'),
('Siano', 'Campania'),
('San Pancrazio Salentino', 'Puglia'),
('Montescaglioso', 'Basilicata'),
('Montemarciano', 'Marche'),
('Fino Mornasco', 'Lombardy'),
('Argelato', 'Emilia-Romagna'),
('Crosia', 'Calabria'),
('Campobello di Licata', 'Sicilia'),
('Lurate Caccivio', 'Lombardy'),
('Mori', 'Trentino-Alto Adige'),
('Trescore Balneario', 'Lombardy'),
('Castrolibero', 'Calabria'),
('Garlasco', 'Lombardy'),
('Poggio Renatico', 'Emilia-Romagna'),
('Boves', 'Piedmont'),
('Conselice', 'Emilia-Romagna'),
('Sant’Egidio alla Vibrata', 'Abruzzo'),
('Ruffano', 'Puglia'),
('Cuorgnè', 'Piedmont'),
('Deruta', 'Umbria'),
('Dolianova', 'Sardegna'),
('Recco', 'Liguria'),
('Matelica', 'Marche'),
('Porto Tolle', 'Veneto'),
('Bellinzago Novarese', 'Piedmont'),
('Castel Bolognese', 'Emilia-Romagna'),
('Santo Stefano di Magra', 'La Spezia'),
('Mareno di Piave', 'Veneto'),
('Zafferana Etnea', 'Sicilia'),
('Sorbolo', 'Emilia-Romagna'),
('Gassino Torinese', 'Piedmont'),
('Nepi', 'Lazio'),
('Elmas', 'Sardegna'),
('Cavriglia', 'Tuscany'),
('Piombino Dese', 'Veneto'),
('Marano Vicentino', 'Veneto'),
('Resana', 'Veneto'),
('Fiumefreddo di Sicilia', 'Sicilia'),
('Mendicino', 'Calabria'),
('Traversetolo', 'Emilia-Romagna'),
('Castelleone', 'Lombardy'),
('Foiano della Chiana', 'Tuscany'),
('Capriolo', 'Lombardy'),
('San Giovanni in Marignano', 'Emilia-Romagna'),
('Fossombrone', 'Marche'),
('Broni', 'Lombardy'),
('Aragona', 'Sicilia'),
('Santa Teresa di Riva', 'Sicilia'),
('Aradeo', 'Puglia'),
('Gavirate', 'Lombardy'),
('Maserada sul Piave', 'Veneto'),
('Pasian di Prato', 'Friuli-Venezia Giulia'),
('Loria', 'Veneto'),
('Giardini', 'Sicilia'),
('Filottrano', 'Marche'),
('Pizzo', 'Calabria'),
('Mosciano Sant’Angelo', 'Abruzzo'),
('Treia', 'Marche'),
('Brugnera', 'Friuli-Venezia Giulia'),
('Carignano', 'Piedmont'),
('Borgosatollo', 'Lombardy'),
('Vignate', 'Lombardy'),
('Villa Castelli', 'Puglia'),
('Belvedere Marittimo', 'Calabria'),
('Castellabate', 'Campania'),
('San Marzano di San Giuseppe', 'Puglia'),
('Vanzago', 'Lombardy'),
('Cherasco', 'Piedmont'),
('Luzzi', 'Calabria'),
('Troina', 'Sicilia'),
('Istrana', 'Veneto'),
('Segni', 'Lazio'),
('Cermenate', 'Lombardy'),
('Folignano', 'Marche'),
('Iseo', 'Lombardy'),
('Magnago', 'Lombardy'),
('Santa Lucia di Piave', 'Veneto'),
('Vittuone', 'Lombardy'),
('Costa Volpino', 'Lombardy'),
('Inverigo', 'Lombardy'),
('Gaggiano', 'Lombardy'),
('Podenzano', 'Emilia-Romagna'),
('Savignano sul Panaro', 'Emilia-Romagna'),
('Maserà di Padova', 'Veneto'),
('Sant’Agnello', 'Campania'),
('Santa Margherita Ligure', 'Liguria'),
('Cogoleto', 'Liguria'),
('Vaprio d’Adda', 'Lombardy'),
('Reggiolo', 'Emilia-Romagna'),
('Serramanna', 'Sardegna'),
('Gonzaga', 'Lombardy'),
('Soverato Marina', 'Calabria'),
('Trebisacce', 'Calabria'),
('Asolo', 'Veneto'),
('Castagneto Carducci', 'Tuscany'),
('Martano', 'Puglia'),
('Malalbergo', 'Emilia-Romagna'),
('Castelnuovo Berardenga', 'Tuscany'),
('Aviano', 'Friuli-Venezia Giulia'),
('Oggiono', 'Lombardy'),
('Roccastrada', 'Tuscany'),
('Petilia Policastro', 'Calabria'),
('Monteroni d’Arbia', 'Tuscany'),
('San Sebastiano al Vesuvio', 'Campania'),
('Colorno', 'Emilia-Romagna'),
('Tirano', 'Lombardy'),
('Parabita', 'Puglia'),
('Sorisole', 'Lombardy'),
('Cesa', 'Campania'),
('Pandino', 'Lombardy'),
('Civitella in Val di Chiana', 'Tuscany'),
('Monticello Conte Otto', 'Veneto'),
('Montagnana', 'Veneto'),
('Noventa Vicentina', 'Veneto'),
('Teolo', 'Veneto'),
('Besozzo', 'Lombardy'),
('Gatteo', 'Emilia-Romagna'),
('Montalto di Castro', 'Lazio'),
('Roccapiemonte', 'Campania'),
('Mozzate', 'Lombardy'),
('Lavis', 'Trentino-Alto Adige'),
('Guardiagrele', 'Abruzzo'),
('Tarcento', 'Friuli-Venezia Giulia'),
('Luzzara', 'Mantova'),
('Lacchiarella', 'Lombardy'),
('Cutrofiano', 'Puglia'),
('Legnaro', 'Veneto'),
('Zogno', 'Lombardy'),
('Castel Gandolfo', 'Lazio'),
('Ponte Buggianese', 'Tuscany'),
('Monteforte d’Alpone', 'Veneto'),
('Subiaco', 'Lazio'),
('Soresina', 'Lombardy'),
('Porcari', 'Tuscany'),
('Bovalino Marina', 'Calabria'),
('Ala', 'Trentino-Alto Adige'),
('Flero', 'Lombardy'),
('Felino', 'Emilia-Romagna'),
('Minervino Murge', 'Puglia'),
('La Loggia', 'Piedmont'),
('Albinea', 'Emilia-Romagna'),
('Ceprano', 'Lazio'),
('Brandizzo', 'Piedmont'),
('Gessate', 'Lombardy'),
('Campogalliano', 'Emilia-Romagna'),
('Farra di Soligo', 'Veneto'),
('Vestignè', 'Piedmont'),
('Orte', 'Lazio'),
('Borgoricco', 'Veneto'),
('Triuggio', 'Lombardy'),
('Minerbio', 'Emilia-Romagna'),
('Torre Boldone', 'Lombardy'),
('San Giorgio di Piano', 'Emilia-Romagna'),
('Zanica', 'Lombardy'),
('Monte Porzio Catone', 'Lazio'),
('Rignano sull’Arno', 'Tuscany'),
('Vergiate', 'Lombardy'),
('Trissino', 'Veneto'),
('Missaglia', 'Lombardy'),
('Morlupo', 'Lazio'),
('Lequile', 'Puglia'),
('Castelbuono', 'Sicilia'),
('Laveno-Mombello', 'Lombardy'),
('Casorate Primo', 'Lombardy'),
('Viagrande', 'Sicilia'),
('Monte San Savino', 'Tuscany'),
('Erchie', 'Puglia'),
('Palazzolo Acreide', 'Sicilia'),
('Coccaglio', 'Lombardy'),
('Pianella', 'Abruzzo'),
('Vicopisano', 'Tuscany'),
('Volvera', 'Piedmont'),
('San Giuseppe Iato', 'Sicilia'),
('Roverbella', 'Lombardy'),
('Clusone', 'Lombardy'),
('Inveruno', 'Lombardy'),
('Bruino', 'Piedmont'),
('Casapulla', 'Campania'),
('Dorgali', 'Sardegna'),
('San Gavino Monreale', 'Sardegna'),
('Ferrandina', 'Basilicata'),
('Breganze', 'Veneto'),
('Gavorrano', 'Tuscany'),
('Spello', 'Umbria'),
('Castelnuovo di Porto', 'Lazio'),
('Sortino', 'Sicilia'),
('Chiusi', 'Tuscany'),
('Santa Venerina', 'Sicilia'),
('Brembate', 'Lombardy'),
('Cagli', 'Marche'),
('Galbiate', 'Lombardy'),
('Calvisano', 'Lombardy'),
('Ittiri', 'Sardegna'),
('Ronciglione', 'Lazio'),
('Boville Ernica', 'Lazio'),
('Striano', 'Campania'),
('Santhià', 'Piedmont'),
('Zoppola', 'Friuli-Venezia Giulia'),
('Fermignano', 'Marche'),
('Pietra Ligure', 'Liguria'),
('Villafranca Tirrena', 'Sicilia'),
('Cologna Veneta', 'Veneto'),
('Sanluri', 'Sardegna'),
('Castelnovo di Sotto', 'Emilia-Romagna'),
('Sandrigo', 'Veneto'),
('Nogara', 'Veneto'),
('Castegnato', 'Lombardy'),
('Concordia sulla Secchia', 'Emilia-Romagna'),
('Prata di Pordenone', 'Friuli-Venezia Giulia'),
('Pogliano Milanese', 'Lombardy'),
('Casarsa della Delizia', 'Friuli-Venezia Giulia'),
('Caprino Veronese', 'Veneto'),
('Tombolo', 'Veneto'),
('Airola', 'Campania'),
('Calusco d’Adda', 'Lombardy'),
('Bientina', 'Tuscany'),
('Sala Bolognese', 'Emilia-Romagna'),
('Vado Ligure', 'Liguria'),
('Tuscania', 'Lazio'),
('Pino Troinese', 'Piedmont'),
('Trevi', 'Umbria'),
('Vallo della Lucania', 'Campania'),
('Ponte di Piave', 'Veneto'),
('Toritto', 'Puglia'),
('San Damiano d’Asti', 'Piedmont'),
('Castelnuovo di Magra', 'Liguria'),
('Piovene Rocchette', 'Veneto'),
('Fiesso d’Artico', 'Veneto'),
('Altavilla Milicia', 'Sicilia'),
('San Sperate', 'Sardegna'),
('Serramazzoni', 'Emilia-Romagna'),
('Cuggiono', 'Lombardy'),
('Soriano nel Cimino', 'Lazio'),
('Massa Marittima', 'Tuscany'),
('Taglio di Po', 'Veneto'),
('Fabrica di Roma', 'Lazio'),
('Salice Salentino', 'Puglia'),
('Ponte nell’Alpi', 'Veneto'),
('Albano Sant’Alessandro', 'Lombardy'),
('Sirmione', 'Lombardy'),
('Decimomannu', 'Sardegna'),
('Agira', 'Sicilia'),
('Monte Urano', 'Marche'),
('Vicchio', 'Tuscany'),
('Petrosino', 'Sicilia'),
('Boiano', 'Molise'),
('Verolanuova', 'Lombardy'),
('Capriate San Gervasio', 'Lombardy'),
('San Cesario di Lecce', 'Puglia'),
('Fusignano', 'Emilia-Romagna'),
('Paliano', 'Lazio'),
('Cariati', 'Calabria'),
('Racalmuto', 'Sicilia'),
('Rivolta d’Adda', 'Lombardy'),
('Caccamo', 'Sicilia'),
('Rossano Veneto', 'Veneto'),
('Solarino', 'Sicilia'),
('Chiaramonte Gulfi', 'Sicilia'),
('Vobarno', 'Lombardy'),
('Fuscaldo', 'Calabria'),
('Quarto d’Altino', 'Veneto'),
('Cervaro', 'Lazio'),
('Leporano', 'Puglia'),
('Verdello', 'Lombardy'),
('Campomarino', 'Molise'),
('Fontaniva', 'Veneto'),
('Villa Guardia', 'Lombardy'),
('Novoli', 'Puglia'),
('Fara Gera d’Adda', 'Lombardy'),
('None', 'Piedmont'),
('Montorio al Vomano', 'Abruzzo'),
('Grottaminarda', 'Campania'),
('Caerano di San Marco', 'Veneto'),
('Levico Terme', 'Trentino-Alto Adige'),
('Gattinara', 'Piedmont'),
('San Daniele del Friuli', 'Friuli-Venezia Giulia'),
('Monte San Giusto', 'Marche'),
('Pisogne', 'Lombardy'),
('Motta Visconti', 'Lombardy'),
('Maracalagonis', 'Sardegna'),
('Casteltermini', 'Sicilia'),
('Tavullia', 'Marche'),
('Borgonovo Val Tidone', 'Emilia-Romagna'),
('San Giovanni Gemini', 'Sicilia'),
('Meta', 'Campania'),
('Cellole', 'Campania'),
('Cartoceto', 'Marche'),
('Bosa', 'Sardegna'),
('Limena', 'Veneto'),
('Mariglianella', 'Campania'),
('Portico di Caserta', 'Campania'),
('Marnate', 'Lombardy'),
('Campoformido', 'Friuli-Venezia Giulia'),
('Gravellona Toce', 'Piedmont'),
('Cumiana', 'Piedmont'),
('Colico', 'Lombardy'),
('Arcugnano', 'Veneto'),
('Bolano', 'Liguria'),
('Toscolano', 'Lombardy'),
('Breda di Piave', 'Veneto'),
('Palagianello', 'Puglia'),
('Origgio', 'Lombardy'),
('Serra Riccò', 'Liguria'),
('Crescentino', 'Piedmont'),
('Avella', 'Campania'),
('Sacrofano', 'Lazio'),
('Rovellasca', 'Lombardy'),
('Teggiano', 'Campania'),
('Marmirolo', 'Lombardy'),
('Rizziconi', 'Calabria'),
('Torrile', 'Emilia-Romagna'),
('San Gimignano', 'Tuscany'),
('Pantelleria', 'Trapani'),
('Tavernelle in Val di Pesa', 'Tuscany'),
('Pelago', 'Tuscany'),
('Appiano Gentile', 'Lombardy'),
('Vigliano Biellese', 'Piedmont'),
('Manziana', 'Lazio'),
('Pasiano', 'Friuli-Venezia Giulia'),
('Carpaneto Piacentino', 'Emilia-Romagna'),
('Fivizzano', 'Tuscany'),
('Vietri sul Mare', 'Campania'),
('Cairate', 'Lombardy'),
('Recale', 'Campania'),
('Loreggia', 'Veneto'),
('Barge', 'Piedmont'),
('Agerola', 'Campania'),
('Santa Maria di Licodia', 'Sicilia'),
('Tricesimo', 'Friuli-Venezia Giulia'),
('Città della Pieve', 'Umbria'),
('Vico del Gargano', 'Puglia'),
('Castiglione Olona', 'Lombardy'),
('Vergato', 'Emilia-Romagna'),
('Costabissara', 'Veneto'),
('Mozzecane', 'Mantova'),
('Soncino', 'Lombardy'),
('Stra', 'Veneto'),
('Vigarano Mainarda', 'Emilia-Romagna'),
('Naro', 'Sicilia'),
('Brisighella', 'Emilia-Romagna'),
('Castellalto', 'Abruzzo'),
('Carmignano di Brenta', 'Veneto'),
('Curno', 'Lombardy'),
('Mirabella Eclano', 'Campania'),
('Lodi Vecchio', 'Lombardy'),
('Sonnino', 'Lazio'),
('Candelo', 'Piedmont'),
('Cologne', 'Lombardy'),
('Pratola Peligna', 'Abruzzo'),
('Nicolosi', 'Sicilia'),
('Campofelice di Roccella', 'Sicilia'),
('Caluso', 'Piedmont'),
('Lamporecchio', 'Tuscany'),
('Roccasecca', 'Lazio'),
('Cotignola', 'Emilia-Romagna'),
('San Giórgio di Nogaro', 'Friuli-Venezia Giulia'),
('Vitulazio', 'Campania'),
('San Zenone', 'Veneto'),
('Bovezzo', 'Lombardy'),
('Grumello del Monte', 'Lombardy'),
('Vedano Olona', 'Lombardy'),
('Torregrotta', 'Sicilia'),
('San Colombano al Lambro', 'Lombardy'),
('San Marco Argentano', 'Calabria'),
('Sparanise', 'Campania'),
('Borgetto', 'Sicilia'),
('Zelo Buon Persico', 'Lombardy'),
('Loreto Aprutino', 'Abruzzo'),
('Tito', 'Basilicata'),
('Pederobba', 'Veneto'),
('Cavenago di Brianza', 'Lombardy'),
('Cormòns', 'Friuli-Venezia Giulia'),
('Sant’Agata Bolognese', 'Emilia-Romagna'),
('Volta Mantovana', 'Lombardy'),
('Forte dei Marmi', 'Tuscany'),
('Castel Madama', 'Lazio'),
('Carnate', 'Lombardy'),
('Marcellina', 'Lazio'),
('Vezzano Ligure', 'Liguria'),
('Curtarolo', 'Veneto'),
('Chiavenna', 'Lombardy'),
('Manciano', 'Tuscany'),
('Staranzano', 'Friuli-Venezia Giulia'),
('Luserna San Giovanni', 'Piedmont'),
('Venegono Superiore', 'Lombardy'),
('Castiglione della Pescaia', 'Tuscany'),
('Poviglio', 'Emilia-Romagna'),
('Torrita di Siena', 'Tuscany'),
('Santa Giustina in Colle', 'Veneto'),
('Rufina', 'Tuscany'),
('Militello in Val di Catania', 'Sicilia'),
('Binasco', 'Lombardy'),
('Isola delle Femmine', 'Sicilia'),
('Carinola', 'Campania'),
('Turbigo', 'Lombardy'),
('Povegliano Veronese', 'Veneto'),
('Campagna Lupia', 'Veneto'),
('Camerano', 'Marche'),
('Montalbano Ionico', 'Basilicata'),
('Montecosaro', 'Marche'),
('Roggiano Gravina', 'Calabria'),
('Corte Franca', 'Lombardy'),
('Cagnano Varano', 'Puglia'),
('Pontremoli', 'Tuscany'),
('Castello di Godego', 'Veneto'),
('Longiano', 'Emilia-Romagna'),
('Sennori', 'Sardegna'),
('Regalbuto', 'Sicilia'),
('Sant’Angelo di Piove di Sacco', 'Veneto'),
('Adro', 'Lombardy'),
('Cimitile', 'Campania'),
('Capri', 'Campania'),
('Mezzolombardo', 'Trentino-Alto Adige'),
('Arpino', 'Lazio'),
('Bardolino', 'Veneto'),
('Varallo', 'Piedmont'),
('Quiliano', 'Liguria'),
('Galliera Veneta', 'Veneto'),
('Spinetoli', 'Marche'),
('Melissano', 'Puglia'),
('Novafeltria', 'Marche'),
('Pontevico', 'Lombardy'),
('Brugine', 'Veneto'),
('Roccadaspide', 'Campania'),
('Campli', 'Abruzzo'),
('Caulonia', 'Calabria'),
('Soave', 'Veneto'),
('Camerota', 'Campania'),
('Sassoferrato', 'Marche'),
('Trino', 'Piedmont'),
('Altavilla Silentina', 'Campania'),
('Montecassiano', 'Marche'),
('Urbania', 'Marche'),
('Asciano', 'Tuscany'),
('Pieve di Cento', 'Emilia-Romagna'),
('Rivergaro', 'Emilia-Romagna'),
('Buttapietra', 'Veneto'),
('Vernole', 'Puglia'),
('Gioiosa Ionica', 'Calabria'),
('Dronero', 'Piedmont'),
('Passirano', 'Lombardy'),
('Chianciano Terme', 'Tuscany'),
('Orosei', 'Sardegna'),
('Pegognaga', 'Lombardy'),
('Fossò', 'Veneto'),
('Grazzanise', 'Campania'),
('San Benedetto Po', 'Lombardy'),
('Fontanellato', 'Emilia-Romagna'),
('Canicattini Bagni', 'Sicilia'),
('Cavezzo', 'Emilia-Romagna'),
('Baricella', 'Emilia-Romagna'),
('Carosino', 'Puglia'),
('Solesino', 'Veneto'),
('Olginate', 'Lombardy'),
('Cordignano', 'Veneto'),
('Morciano di Romagna', 'Emilia-Romagna'),
('Oliena', 'Sardegna'),
('Barlassina', 'Lombardy'),
('Calimera', 'Puglia'),
('Cles', 'Trentino-Alto Adige'),
('San Filippo della Mela', 'Sicilia'),
('Centallo', 'Piedmont'),
('Bellante', 'Abruzzo'),
('Senise', 'Basilicata'),
('Borgo a Mozzano', 'Tuscany'),
('Roncoferraro', 'Lombardy'),
('Spezzano Albanese', 'Calabria'),
('Cassolnovo', 'Lombardy'),
('Scorrano', 'Puglia'),
('Vallecrosia', 'Liguria'),
('Vazzola', 'Veneto'),
('Santi Cosma e Damiano', 'Lazio'),
('Serino', 'Campania'),
('Saltara', 'Marche'),
('Noventa di Piave', 'Veneto'),
('Anacapri', 'Campania'),
('San Fior di Sopra', 'Veneto'),
('Lazise', 'Veneto'),
('Vipiteno', 'Trentino-Alto Adige'),
('Camerino', 'Marche'),
('Cambiago', 'Lombardy'),
('Borgo', 'Trentino-Alto Adige'),
('Lignano Sabbiadoro', 'Friuli-Venezia Giulia'),
('Gioiosa Marea', 'Sicilia'),
('Roccarainola', 'Campania'),
('Busseto', 'Emilia-Romagna'),
('Villasor', 'Sardegna'),
('Pozzuolo del Friuli', 'Friuli-Venezia Giulia'),
('Manoppello', 'Abruzzo'),
('Montelabbate', 'Marche'),
('Pignola', 'Basilicata'),
('Borgo Val di Taro', 'Emilia-Romagna'),
('Nole', 'Piedmont'),
('Sommatino', 'Sicilia'),
('Spino d’Adda', 'Lombardy'),
('Zibido San Giacomo', 'Lombardy'),
('Marzabotto', 'Emilia-Romagna'),
('Ferno', 'Lombardy'),
('Campomorone', 'Liguria'),
('Sant’Agostino', 'Emilia-Romagna'),
('Mapello', 'Lombardy'),
('Mercato Saraceno', 'Emilia-Romagna'),
('San Vincenzo', 'Tuscany'),
('Pietraperzia', 'Sicilia'),
('Cerano', 'Piedmont'),
('Martignacco', 'Friuli-Venezia Giulia'),
('Nova Siri', 'Basilicata'),
('Monte San Vito', 'Marche'),
('Caraglio', 'Piedmont'),
('Santa Giustina', 'Veneto'),
('Mesola', 'Emilia-Romagna'),
('Villa di Serio', 'Lombardy'),
('Cava Manara', 'Lombardy'),
('Lercara Friddi', 'Sicilia'),
('Settimo San Pietro', 'Sardegna'),
('Tagliacozzo', 'Abruzzo'),
('Olevano sul Tusciano', 'Campania'),
('Mileto', 'Calabria'),
('Ostiglia', 'Lombardy'),
('Robecco sul Naviglio', 'Lombardy'),
('Montegiorgio', 'Marche'),
('Carnago', 'Lombardy'),
('Curinga', 'Calabria'),
('Cittaducale', 'Lazio'),
('Cernobbio', 'Lombardy'),
('Praia a Mare', 'Calabria'),
('Sapri', 'Campania'),
('Casteggio', 'Lombardy'),
('Castel di Sangro', 'Abruzzo'),
('Alliste', 'Puglia'),
('Notaresco', 'Abruzzo'),
('Carapelle', 'Puglia'),
('Sarnico', 'Lombardy'),
('Salgareda', 'Veneto'),
('Larino', 'Molise'),
('Nervesa della Battaglia', 'Veneto'),
('Villa d’Almè', 'Lombardy'),
('Olevano Romano', 'Lazio'),
('Torgiano', 'Umbria'),
('Zanè', 'Veneto'),
('Arconate', 'Lombardy'),
('Sutri', 'Lazio'),
('Brendola', 'Veneto'),
('Poggio Rusco', 'Lombardy'),
('Villadossola', 'Piedmont'),
('Montenero di Bisaccia', 'Molise'),
('Fabbrico', 'Emilia-Romagna'),
('Serra San Bruno', 'Calabria'),
('Avetrana', 'Puglia'),
('Marina di Gioiosa Ionica', 'Calabria'),
('Marcaria', 'Lombardy'),
('Dozza', 'Emilia-Romagna'),
('Castello d’Argile', 'Emilia-Romagna'),
('San Marco Evangelista', 'Campania'),
('Mede', 'Lombardy'),
('San Cipriano Picentino', 'Campania'),
('San Donaci', 'Puglia'),
('Gorle', 'Lombardy'),
('Livigno', 'Lombardy'),
('Pollenza', 'Marche'),
('Montesano sulla Marcellana', 'Campania'),
('Montebello Vicentino', 'Veneto'),
('Marineo', 'Sicilia'),
('Calatafimi', 'Sicilia'),
('Cellino San Marco', 'Puglia'),
('Gonnosfanàdiga', 'Sardegna'),
('Ceriano Laghetto', 'Lombardy'),
('Strongoli', 'Calabria'),
('Vairano Patenora', 'Campania'),
('Spinazzola', 'Puglia'),
('Pontenure', 'Emilia-Romagna'),
('Buia', 'Friuli-Venezia Giulia'),
('Bolzano Vicentino', 'Veneto'),
('Verzuolo', 'Piedmont'),
('Cinquefrondi', 'Calabria'),
('Gualtieri', 'Emilia-Romagna'),
('Labico', 'Lazio'),
('Piedimonte San Germano', 'Lazio'),
('Pizzighettone', 'Lombardy'),
('Codevigo', 'Veneto'),
('Canova', 'Lombardy'),
('San Cesario sul Panaro', 'Emilia-Romagna'),
('Rosolina', 'Veneto'),
('Sammichele di Bari', 'Puglia'),
('Gradisca d’Isonzo', 'Friuli-Venezia Giulia'),
('Roccella Ionica', 'Calabria'),
('Sant’Arcangelo', 'Basilicata'),
('Balestrate', 'Sicilia'),
('Asiago', 'Veneto'),
('Capranica', 'Lazio'),
('Almese', 'Piedmont'),
('Vidigulfo', 'Lombardy'),
('Dairago', 'Lombardy'),
('Calci', 'Tuscany'),
('Arquata Scrivia', 'Piedmont'),
('Albanella', 'Campania'),
('Poggio Mirteto', 'Lazio'),
('Cisano Bergamasco', 'Lombardy'),
('Landriano', 'Lombardy'),
('Monzuno', 'Emilia-Romagna'),
('Subbiano', 'Tuscany'),
('Alessano', 'Puglia'),
('San Marcello Pistoiese', 'Tuscany'),
('Sesto al Reghena', 'Friuli-Venezia Giulia'),
('Capannoli', 'Tuscany'),
('Fossacesia', 'Abruzzo'),
('Mesoraca', 'Calabria'),
('Albiate', 'Lombardy'),
('Buttigliera Alta', 'Piedmont'),
('Lesina', 'Puglia'),
('San Giorgio in Bosco', 'Veneto'),
('Meolo', 'Veneto'),
('Gallicano nel Lazio', 'Lazio'),
('Susa', 'Piedmont'),
('Caneva', 'Friuli-Venezia Giulia'),
('Santa Margherita di Belice', 'Sicilia'),
('Robbiate', 'Lombardy'),
('Abbadia San Salvatore', 'Tuscany'),
('Sommariva del Bosco', 'Piedmont'),
('Monte San Biagio', 'Lazio'),
('Tropea', 'Calabria'),
('Recoaro Terme', 'Veneto'),
('Fagagna', 'Friuli-Venezia Giulia'),
('San Martino Siccomario', 'Lombardy'),
('Porto Cesareo', 'Puglia'),
('Quinzano d’Oglio', 'Lombardy'),
('Cornuda', 'Veneto'),
('Mattinata', 'Puglia'),
('Tortorici', 'Sicilia'),
('San Michele Salentino', 'Puglia'),
('Medolla', 'Emilia-Romagna'),
('Marcallo con Casone', 'Lombardy'),
('Almenno San Bartolomeo', 'Lombardy'),
('Arcole', 'Veneto'),
('San Canzian d’lsonzo', 'Friuli-Venezia Giulia'),
('Belgioioso', 'Lombardy'),
('Trasacco', 'Abruzzo'),
('Cammarata', 'Sicilia'),
('Fossalta di Portogruaro', 'Veneto'),
('Castelgomberto', 'Veneto'),
('Maiolati Spontini', 'Marche'),
('Silandro', 'Trentino-Alto Adige'),
('Montebello Ionico', 'Calabria'),
('Sernaglia della Battaglia', 'Veneto'),
('Carloforte', 'Sardegna'),
('Villa Cortese', 'Lombardy'),
('Ghisalba', 'Lombardy'),
('Strambino', 'Piedmont'),
('Ascoli Satriano', 'Puglia'),
('Tortora', 'Calabria'),
('Piana degli Albanesi', 'Sicilia'),
('San Polo d’Enza in Caviano', 'Emilia-Romagna'),
('Nicotera', 'Calabria'),
('Lioni', 'Campania'),
('Poppi', 'Tuscany'),
('Sumirago', 'Lombardy'),
('Domusnovas', 'Sardegna'),
('Montelepre', 'Sicilia'),
('Villaverla', 'Veneto'),
('San Giovanni al Natisone', 'Friuli-Venezia Giulia'),
('Rio Saliceto', 'Emilia-Romagna'),
('Ravarino', 'Emilia-Romagna'),
('Venegono Inferiore', 'Lombardy'),
('Ceggia', 'Veneto'),
('Rovello Porro', 'Lombardy'),
('Torreglia', 'Veneto'),
('Monterenzio', 'Emilia-Romagna'),
('Bellona', 'Campania'),
('Crocetta del Montello', 'Veneto'),
('Remanzacco', 'Friuli-Venezia Giulia'),
('Casalbordino', 'Abruzzo'),
('Sermide', 'Lombardy'),
('Motta San Giovanni', 'Calabria'),
('Cadeo', 'Emilia-Romagna'),
('Siziano', 'Lombardy'),
('Vizzini', 'Sicilia'),
('Gaiarine', 'Veneto'),
('Luco dei Marsi', 'Abruzzo'),
('San Lucido', 'Calabria'),
('Collecorvino', 'Abruzzo'),
('Pantigliate', 'Lombardy'),
('Sant’Elia Fiumerapido', 'Lazio'),
('Vernio', 'Tuscany'),
('San Benigno Canavese', 'Piedmont'),
('Godega di Sant’Urbano', 'Veneto'),
('Offanengo', 'Lombardy'),
('Ostellato', 'Emilia-Romagna'),
('San Giovanni Suèrgiu', 'Sardegna'),
('Guidizzolo', 'Lombardy'),
('Brignano Gera d’Adda', 'Lombardy'),
('Cambiano', 'Piedmont'),
('Fornovo di Taro', 'Emilia-Romagna'),
('Pimonte', 'Campania'),
('Ronco all’Adige', 'Veneto'),
('Bagni di Lucca', 'Tuscany'),
('Serravalle Scrivia', 'Piedmont'),
('Poggiardo', 'Puglia'),
('Castelsardo', 'Sardegna'),
('Calcinate', 'Lombardy'),
('Collepasso', 'Puglia'),
('Bagnolo Piemonte', 'Piedmont'),
('Mel', 'Veneto'),
('Gualdo Cattaneo', 'Umbria'),
('Pignataro Maggiore', 'Campania'),
('Serradifalco', 'Sicilia'),
('Borso del Grappa', 'Veneto'),
('Genazzano', 'Lazio'),
('Roveredo in Piano', 'Friuli-Venezia Giulia'),
('Bagnolo San Vito', 'Lombardy'),
('Castelnuovo di Garfagnana', 'Tuscany'),
('Maiano', 'Friuli-Venezia Giulia'),
('Cavaion Veronese', 'Veneto'),
('Montalcino', 'Tuscany'),
('Truccazzano', 'Lombardy'),
('Villa Bartolomea', 'Veneto'),
('Bagno di Romagna', 'Emilia-Romagna'),
('Picerno', 'Basilicata'),
('Diano Marina', 'Liguria'),
('Sannicola', 'Puglia'),
('Loro Ciuffenna', 'Tuscany'),
('Ascea', 'Campania'),
('Torrebelvicino', 'Veneto'),
('Cortina d’Ampezzo', 'Veneto'),
('Cavaria', 'Lombardy'),
('Sambuca di Sicilia', 'Sicilia'),
('Robbio', 'Lombardy'),
('Villanuova sul clisi', 'Lombardy'),
('Girifalco', 'Calabria'),
('Bussoleno', 'Piedmont'),
('Costigliole d’Asti', 'Piedmont'),
('Quinto Vicentino', 'Veneto'),
('Palosco', 'Lombardy'),
('Naturno', 'Trentino-Alto Adige'),
('Stornara', 'Puglia'),
('Otranto', 'Puglia'),
('Villanova Mondovì', 'Piedmont'),
('Cellamare', 'Puglia'),
('Rosate', 'Lombardy'),
('Rudiano', 'Lombardy'),
('Ceva', 'Piedmont'),
('Corigliano d’Otranto', 'Puglia'),
('Brolo', 'Sicilia'),
('Rogliano', 'Calabria'),
('San Dorligo della Valle', 'Friuli-Venezia Giulia'),
('Campo San Martino', 'Veneto'),
('Fontanelle', 'Veneto'),
('Gattatico', 'Emilia-Romagna'),
('San Paolo di Civitate', 'Puglia'),
('Alezio', 'Puglia'),
('Cogorno', 'Liguria'),
('Spirano', 'Lombardy'),
('Uzzano', 'Tuscany'),
('Cancello', 'Campania'),
('Gabicce', 'Marche'),
('Passignano sul Trasimeno', 'Umbria'),
('Santorso', 'Veneto'),
('Nocera Umbra', 'Umbria'),
('Trevignano Romano', 'Lazio'),
('Pomarance', 'Tuscany'),
('Ciserano', 'Lombardy'),
('Genzano di Lucania', 'Basilicata'),
('Casorate Sempione', 'Lombardy'),
('Villanova d’Asti', 'Piedmont'),
('Castelverde', 'Lombardy'),
('San Secondo Parmense', 'Emilia-Romagna'),
('Longare', 'Veneto'),
('Guagnano', 'Puglia'),
('Riolo Terme', 'Emilia-Romagna'),
('Rocca di Neto', 'Calabria'),
('Almenno San Salvatore', 'Lombardy'),
('San Giorgio Piacentino', 'Emilia-Romagna'),
('Arce', 'Lazio'),
('Acque Dolci', 'Sicilia'),
('Romentino', 'Piedmont'),
('San Donato di Lecce', 'Puglia'),
('Gossolengo', 'Emilia-Romagna'),
('Ospedaletto Euganeo', 'Veneto'),
('Casaleone', 'Veneto'),
('Candiolo', 'Piedmont'),
('Buti', 'Tuscany'),
('Campagnola Emilia', 'Emilia-Romagna'),
('Canale', 'Piedmont'),
('Gozzano', 'Piedmont'),
('Sala Baganza', 'Emilia-Romagna'),
('Fontevivo', 'Emilia-Romagna'),
('Panicale', 'Umbria'),
('Almè', 'Lombardy'),
('Dello', 'Lombardy'),
('Brescello', 'Emilia-Romagna'),
('Grotte', 'Sicilia'),
('Casoli', 'Abruzzo'),
('Trivero', 'Piedmont'),
('Monteiasi', 'Puglia'),
('Apice', 'Campania'),
('Montefalco', 'Umbria'),
('Misinto', 'Lombardy'),
('Pavia di Udine', 'Friuli-Venezia Giulia'),
('Ceriale', 'Liguria'),
('Custonaci', 'Sicilia'),
('Maiori', 'Campania'),
('Peveragno', 'Piedmont'),
('Camporosso', 'Liguria'),
('Besnate', 'Lombardy'),
('Quistello', 'Lombardy'),
('Cilavegna', 'Lombardy'),
('Angera', 'Lombardy'),
('Busalla', 'Liguria'),
('Chiaravalle Centrale', 'Calabria'),
('Anghiari', 'Tuscany'),
('Carcare', 'Liguria'),
('Davoli', 'Calabria'),
('Marsico Vetere', 'Basilicata'),
('San Tammaro', 'Campania'),
('Bracigliano', 'Campania'),
('Villa del Conte', 'Veneto'),
('Dicomano', 'Tuscany'),
('Castiglione dei Pepoli', 'Emilia-Romagna'),
('Bentivoglio', 'Emilia-Romagna'),
('Cavour', 'Piedmont'),
('Caiazzo', 'Campania'),
('Moglia', 'Lombardy'),
('Mezzocorona', 'Trentino-Alto Adige'),
('Solbiate Olona', 'Lombardy'),
('Cotronei', 'Calabria'),
('Borgo San Giacomo', 'Lombardy'),
('Cavallermaggiore', 'Piedmont'),
('Casorezzo', 'Lombardy'),
('Galliera', 'Emilia-Romagna'),
('Lagonegro', 'Basilicata'),
('Acquapendente', 'Lazio'),
('Certosa di Pavia', 'Lombardy'),
('Corsano', 'Puglia'),
('Povoletto', 'Friuli-Venezia Giulia'),
('Sannazzaro de’ Burgondi', 'Lombardy'),
('Soleto', 'Puglia'),
('Palmanova', 'Friuli-Venezia Giulia'),
('Torchiarolo', 'Puglia'),
('Caprarola', 'Lazio'),
('Montepaone', 'Calabria'),
('Gandino', 'Lombardy'),
('Santa Teresa Gallura', 'Sardegna'),
('Vanzaghello', 'Lombardy'),
('Albisola Marina', 'Liguria'),
('Lanusei', 'Sardegna'),
('Lurago d’Erba', 'Lombardy'),
('Padula', 'Campania'),
('Arienzo', 'Campania'),
('Centuripe', 'Sicilia'),
('Villapiana', 'Calabria'),
('Casalserugo', 'Veneto'),
('Cupra Marittima', 'Marche'),
('Forino', 'Campania'),
('San Cipirello', 'Sicilia'),
('Gazzo Veronese', 'Veneto'),
('Boretto', 'Emilia-Romagna'),
('Basiliano', 'Friuli-Venezia Giulia'),
('Stornarella', 'Puglia'),
('Muro Lucano', 'Basilicata'),
('Nereto', 'Abruzzo'),
('Codognè', 'Veneto'),
('Linguaglossa', 'Sicilia'),
('Limana', 'Veneto'),
('Castelvetro Piacentino', 'Emilia-Romagna'),
('Rivanazzano', 'Lombardy'),
('Monte Libretti', 'Lazio'),
('Casal Velino', 'Campania'),
('Camposano', 'Campania'),
('Sovere', 'Lombardy'),
('Aquino', 'Lazio'),
('Viggiù', 'Lombardy'),
('Sant’Omero', 'Abruzzo'),
('Carsoli', 'Abruzzo'),
('Rapolano Terme', 'Tuscany'),
('Camogli', 'Liguria'),
('Albizzate', 'Lombardy'),
('Gizzeria', 'Calabria'),
('Diamante', 'Calabria'),
('Oppido Mamertina', 'Calabria'),
('Montemiletto', 'Campania'),
('Monticelli d’Ongina', 'Emilia-Romagna'),
('Presicce', 'Puglia'),
('Canino', 'Lazio'),
('Sarroch', 'Sardegna'),
('Ispra', 'Lombardy'),
('Sarcedo', 'Veneto'),
('Botricello', 'Calabria'),
('Calatabiano', 'Sicilia'),
('Polla', 'Campania'),
('Muravera', 'Sardegna'),
('Rodigo', 'Lombardy'),
('Mugnano del Cardinale', 'Campania'),
('San Vito Chietino', 'Abruzzo'),
('Malles Venosta', 'Trentino-Alto Adige'),
('Montanaro', 'Piedmont'),
('Longarone', 'Veneto'),
('Castronno', 'Lombardy'),
('Santa Caterina Villarmosa', 'Sicilia'),
('Esine', 'Lombardy'),
('Ripi', 'Lazio'),
('Guglionesi', 'Molise'),
('Povegliano', 'Veneto'),
('Illasi', 'Veneto'),
('Maruggio', 'Puglia'),
('Vitorchiano', 'Lazio'),
('Castellucchio', 'Lombardy'),
('Chiusa', 'Trentino-Alto Adige'),
('San Pietro di Feletto', 'Veneto'),
('Fragagnano', 'Puglia'),
('Poncarale', 'Lombardy'),
('Neviano', 'Puglia'),
('Lovere', 'Lombardy'),
('Coreglia Antelminelli', 'Tuscany'),
('Laces', 'Trentino-Alto Adige'),
('Tuglie', 'Puglia'),
('Tricarico', 'Basilicata'),
('Giavera del Montello', 'Veneto'),
('Correzzola', 'Veneto'),
('Castrignano del Capo', 'Puglia'),
('Castelnuovo Scrivia', 'Piedmont'),
('Albaredo d’Adige', 'Veneto'),
('Cannobio', 'Piedmont'),
('Favria', 'Piedmont'),
('Giussago', 'Lombardy'),
('Cividate al Piano', 'Lombardy'),
('Gottolengo', 'Lombardy'),
('Celle Ligure', 'Liguria'),
('Trezzano Rosa', 'Lombardy'),
('Chions', 'Friuli-Venezia Giulia'),
('Cerda', 'Sicilia'),
('Marano sul Panaro', 'Emilia-Romagna'),
('Vigone', 'Piedmont'),
('Capistrello', 'Abruzzo'),
('Centola', 'Campania'),
('Bottanuco', 'Lombardy'),
('Vaglia', 'Tuscany'),
('Bucchianico', 'Abruzzo'),
('Campegine', 'Emilia-Romagna'),
('Veronella', 'Veneto'),
('Ardore', 'Calabria'),
('Samassi', 'Sardegna'),
('Portoscuso', 'Sardegna'),
('Amalfi', 'Campania'),
('Barzanò', 'Lombardy'),
('Gagliano del Capo', 'Puglia'),
('Maser', 'Veneto'),
('Colle Umberto', 'Veneto'),
('Assoro', 'Sicilia'),
('Borgo Ticino', 'Piedmont'),
('Maratea', 'Basilicata'),
('Mineo', 'Sicilia'),
('San Giovanni Ilarione', 'Veneto'),
('Canzo', 'Lombardy'),
('Laureana di Borrello', 'Calabria'),
('Grassano', 'Basilicata'),
('Ornago', 'Lombardy'),
('Baselga di Pinè', 'Trentino-Alto Adige'),
('Mansuè', 'Veneto'),
('Pagnacco', 'Friuli-Venezia Giulia'),
('Gazzaniga', 'Lombardy'),
('Melicucco', 'Calabria'),
('Corropoli', 'Abruzzo'),
('Condofuri', 'Calabria'),
('Lagundo', 'Trentino-Alto Adige'),
('Telgate', 'Lombardy'),
('Montecastrilli', 'Umbria'),
('Arosio', 'Lombardy'),
('Villadose', 'Veneto'),
('Bella', 'Basilicata'),
('Bevagna', 'Umbria'),
('Lonate Ceppino', 'Lombardy'),
('Lanzo Torinese', 'Piedmont'),
('Castelbellino', 'Marche'),
('Agnone', 'Molise'),
('Tolfa', 'Lazio'),
('Lesignano de’ Bagni', 'Emilia-Romagna'),
('Lomagna', 'Lombardy'),
('Terranova di Sibari', 'Calabria'),
('Sant’Angelo Romano', 'Lazio'),
('San Gemini', 'Umbria'),
('Gorla Maggiore', 'Lombardy'),
('Spadafora', 'Sicilia'),
('Santo Stefano Ticino', 'Lombardy'),
('Tursi', 'Basilicata'),
('San Ferdinando', 'Calabria'),
('Mornago', 'Lombardy'),
('Porlezza', 'Lombardy'),
('Mortegliano', 'Friuli-Venezia Giulia'),
('Nove', 'Veneto'),
('Gonnesa', 'Sardegna'),
('Offida', 'Marche'),
('Santa Ninfa', 'Sicilia'),
('Rovolon', 'Veneto'),
('Serravalle Sesia', 'Piedmont'),
('Saccolongo', 'Veneto'),
('San Polo di Piave', 'Veneto'),
('Ricadi', 'Calabria'),
('Sassano', 'Campania'),
('Muro Leccese', 'Puglia'),
('San Francesco al Campo', 'Piedmont'),
('Varallo Pombia', 'Piedmont'),
('Guardia Sanframondi', 'Campania'),
('Tregnago', 'Veneto'),
('Licciana Nardi', 'Tuscany'),
('Civitella del Tronto', 'Abruzzo'),
('Stresa', 'Piedmont'),
('Irsina', 'Basilicata'),
('Reana del Roiale', 'Friuli-Venezia Giulia'),
('Arsago Seprio', 'Lombardy'),
('Morcone', 'Campania'),
('Zimella', 'Veneto'),
('San Martino Valle Caudina', 'Campania'),
('Corinaldo', 'Marche'),
('Buccino', 'Campania'),
('Gradara', 'Marche'),
('Norcia', 'Umbria'),
('Scilla', 'Calabria'),
('Baveno', 'Piedmont'),
('Bagnolo Cremasco', 'Lombardy'),
('Monzambano', 'Lombardy'),
('Arcene', 'Lombardy'),
('Cisliano', 'Lombardy'),
('Robecchetto con Induno', 'Lombardy'),
('Popoli', 'Abruzzo'),
('Francolise', 'Campania'),
('Gambassi', 'Tuscany'),
('Senorbì', 'Sardegna'),
('Bassano Romano', 'Lazio'),
('Casale di Scodosia', 'Veneto'),
('Gaggio Montano', 'Emilia-Romagna'),
('Lagosanto', 'Emilia-Romagna'),
('Torrice', 'Lazio'),
('Verolengo', 'Piedmont'),
('Soragna', 'Emilia-Romagna'),
('Arzergrande', 'Veneto'),
('Cupello', 'Abruzzo'),
('San Pellegrino Terme', 'Lombardy'),
('Villarosa', 'Sicilia'),
('Supino', 'Lazio'),
('Palazzo San Gervasio', 'Basilicata'),
('Cropani', 'Calabria'),
('Breno', 'Lombardy'),
('Trichiana', 'Veneto'),
('Marrùbiu', 'Sardegna'),
('Stroncone', 'Umbria'),
('Castel del Piano', 'Tuscany'),
('Serrenti', 'Sardegna'),
('Santa Giusta', 'Sardegna'),
('Lacco Ameno', 'Campania'),
('Aidone', 'Sicilia'),
('Borghetto Santo Spirito', 'Liguria'),
('Agugliano', 'Marche'),
('San Giovanni Bianco', 'Lombardy'),
('Fosdinovo', 'Tuscany'),
('Nocera Terinese', 'Calabria'),
('Osnago', 'Lombardy'),
('Paratico', 'Lombardy'),
('Roccafranca', 'Lombardy'),
('San Costanzo', 'Marche'),
('Torre di Mosto', 'Veneto'),
('Veggiano', 'Veneto'),
('Mirabella Imbaccari', 'Sicilia'),
('Catenanuova', 'Sicilia'),
('Cocquio Trevisago', 'Lombardy'),
('Miglianico', 'Abruzzo'),
('San Martino in Pensilis', 'Molise'),
('Buscate', 'Lombardy'),
('Andrano', 'Puglia'),
('Specchia', 'Puglia'),
('Gambara', 'Lombardy'),
('San Bartolomeo in Galdo', 'Campania'),
('Baiano', 'Campania'),
('Alvignano', 'Campania'),
('Castro dei Volsci', 'Lazio'),
('Caorso', 'Emilia-Romagna'),
('Dogliani', 'Piedmont'),
('Villafranca in Lunigiana', 'Tuscany'),
('Peccioli', 'Tuscany'),
('Sant’Ambrogio di Torino', 'Piedmont'),
('Gonàrs', 'Friuli-Venezia Giulia'),
('Villaputzu', 'Sardegna'),
('Prizzi', 'Sicilia'),
('Azzate', 'Lombardy'),
('Montà', 'Piedmont'),
('Berra', 'Emilia-Romagna'),
('San Vito lo Capo', 'Sicilia'),
('Riva presso Chieri', 'Piedmont'),
('Sarteano', 'Tuscany'),
('Alseno', 'Emilia-Romagna'),
('Cappella Maggiore', 'Veneto'),
('Mordano', 'Emilia-Romagna'),
('Pietramelara', 'Campania'),
('Ponte dell’Olio', 'Emilia-Romagna'),
('Pozzolo Formigaro', 'Piedmont'),
('Isola del Gran Sasso d’Italia', 'Abruzzo'),
('Pian Camuno', 'Lombardy'),
('Cortemaggiore', 'Emilia-Romagna'),
('Acquasparta', 'Umbria'),
('Piancogno', 'Lombardy'),
('Dorno', 'Lombardy'),
('Santo Stefano di Camastra', 'Sicilia'),
('Trivento', 'Molise'),
('Carvico', 'Lombardy'),
('Castel d’Ario', 'Lombardy'),
('Châtillon', 'Valle d’Aosta'),
('Acquarica del Capo', 'Puglia'),
('Castiglione d’Adda', 'Lombardy'),
('Pramaggiore', 'Veneto'),
('Vertova', 'Lombardy'),
('Mistretta', 'Sicilia'),
('San Giorgio della Richinvelda', 'Friuli-Venezia Giulia'),
('Rodano', 'Lombardy'),
('Padenghe sul Garda', 'Lombardy'),
('Castell’Arquato', 'Emilia-Romagna'),
('Brivio', 'Lombardy'),
('Butera', 'Sicilia'),
('Cupramontana', 'Marche'),
('Villafranca Piemonte', 'Piedmont'),
('Condove', 'Piedmont'),
('Barbarano Vicentino', 'Veneto'),
('Pizzoli', 'Abruzzo'),
('Zocca', 'Emilia-Romagna'),
('Torano Castello', 'Calabria'),
('Piglio', 'Lazio'),
('Bricherasio', 'Piedmont'),
('Gragnano Trebbiense', 'Emilia-Romagna'),
('Crevola d’Ossola', 'Piedmont'),
('Firenzuola', 'Tuscany'),
('Storo', 'Trentino-Alto Adige'),
('Grantorto', 'Veneto'),
('Saint-Vincent', 'Valle d’Aosta'),
('Santa Lucia del Mela', 'Sicilia'),
('Calitri', 'Campania'),
('Mogliano', 'Marche'),
('Minerbe', 'Veneto'),
('Villastellone', 'Piedmont'),
('Spezzano Grande', 'Calabria'),
('Polverigi', 'Marche'),
('Edolo', 'Lombardy'),
('Chiesina Uzzanese', 'Tuscany'),
('Monterosi', 'Lazio'),
('Sersale', 'Calabria'),
('Mozzanica', 'Lombardy'),
('Arcade', 'Veneto'),
('Torre Pellice', 'Piedmont'),
('Monsampolo del Tronto', 'Marche'),
('Varna', 'Trentino-Alto Adige'),
('Vailate', 'Lombardy'),
('Palaia', 'Tuscany'),
('Realmonte', 'Sicilia'),
('Predazzo', 'Trentino-Alto Adige'),
('Teglio', 'Lombardy'),
('Carimate', 'Lombardy'),
('Guardavalle', 'Calabria'),
('Rombiolo', 'Calabria'),
('Vignanello', 'Lazio'),
('Druento', 'Piedmont'),
('Terricciola', 'Tuscany'),
('Castellazzo Bormida', 'Piedmont'),
('Ploaghe', 'Sardegna'),
('San Paolo', 'Lombardy'),
('Castel di Iudica', 'Sicilia'),
('Santo Stefano Quisquina', 'Sicilia'),
('Crespano del Grappa', 'Veneto'),
('Castelraimondo', 'Marche'),
('Grignasco', 'Piedmont'),
('Castel Guelfo di Bologna', 'Emilia-Romagna'),
('Sotto il Monte', 'Lombardy'),
('Gropello Cairoli', 'Lombardy'),
('Peschici', 'Puglia'),
('Cigliano', 'Piedmont'),
('Casina', 'Emilia-Romagna'),
('Ormelle', 'Veneto'),
('Borgorose', 'Lazio'),
('Morgano', 'Veneto'),
('Modigliana', 'Emilia-Romagna'),
('Bisacquino', 'Sicilia'),
('San Zenone al Lambro', 'Lombardy'),
('Siculiana', 'Sicilia'),
('Bogliasco', 'Liguria'),
('Solarolo', 'Emilia-Romagna'),
('Ghilarza', 'Sardegna'),
('Torrenova', 'Sicilia'),
('Pedavena', 'Veneto'),
('Capri Leone', 'Sicilia'),
('San Pietro in Gù', 'Veneto'),
('Toano', 'Emilia-Romagna'),
('Grosio', 'Lombardy'),
('Carrù', 'Piedmont'),
('Briatico', 'Calabria'),
('Carpineto Romano', 'Lazio'),
('Latronico', 'Basilicata'),
('Morano Calabro', 'Calabria'),
('Acqualagna', 'Marche'),
('Ischitella', 'Puglia'),
('Calascibetta', 'Sicilia'),
('Supersano', 'Puglia'),
('Visciano', 'Campania'),
('Terlano', 'Trentino-Alto Adige'),
('Comun Nuovo', 'Lombardy'),
('Canneto sull’Oglio', 'Lombardy'),
('Tresigallo', 'Emilia-Romagna'),
('Uggiano la Chiesa', 'Puglia'),
('Castelfrentano', 'Abruzzo'),
('Altomonte', 'Calabria'),
('Scansano', 'Tuscany'),
('Tribano', 'Veneto'),
('Ameglia', 'Liguria'),
('Ronco Scrivia', 'Liguria'),
('Montereale Valcellina', 'Friuli-Venezia Giulia'),
('Usini', 'Sardegna'),
('Barberino di Val d’Elsa', 'Tuscany'),
('Bettona', 'Umbria'),
('Decimoputzu', 'Sardegna'),
('Rapolla', 'Basilicata'),
('Monastier di Treviso', 'Veneto'),
('Capocasale', 'Calabria'),
('Favignana', 'Sicilia'),
('Poiana Maggiore', 'Veneto'),
('Tarzo', 'Veneto'),
('Livorno Ferraris', 'Piedmont'),
('Santa Croce di Magliano', 'Molise'),
('Cannara', 'Umbria'),
('San Quirino', 'Friuli-Venezia Giulia'),
('Montecchia di Crosara', 'Veneto'),
('Anguillara Veneta', 'Veneto'),
('Arcevia', 'Marche'),
('Galzignano', 'Veneto'),
('Arcidosso', 'Tuscany'),
('Amaseno', 'Lazio'),
('Locate Varesino', 'Lombardy'),
('Paglieta', 'Abruzzo'),
('Ponte Lambro', 'Lombardy'),
('Borghetto Lodigiano', 'Lombardy'),
('Sossano', 'Veneto'),
('Vestone', 'Lombardy'),
('Gazzo', 'Veneto'),
('Vigolzone', 'Emilia-Romagna'),
('Grisignano di Zocco', 'Veneto'),
('Loiano', 'Emilia-Romagna'),
('Roana', 'Veneto'),
('Ossona', 'Lombardy'),
('Bianco', 'Calabria'),
('Malgrate', 'Lombardy'),
('Cene', 'Lombardy'),
('Torretta', 'Sicilia'),
('Vezzano sul Crostolo', 'Emilia-Romagna'),
('Revello', 'Piedmont'),
('Sant’Antonio di Susa', 'Piedmont'),
('San Salvatore Monferrato', 'Piedmont'),
('Marcheno', 'Lombardy'),
('Ariano nel Polesine', 'Veneto'),
('Calvenzano', 'Lombardy'),
('Bastiglia', 'Emilia-Romagna'),
('Ripatransone', 'Marche'),
('Palau', 'Sardegna'),
('Tarvisio', 'Friuli-Venezia Giulia'),
('Castelforte', 'Lazio'),
('San Gregorio Magno', 'Campania'),
('Bova Marina', 'Calabria'),
('Sant’Angelo de’ Lombardi', 'Campania'),
('Torrevecchia Teatina', 'Abruzzo'),
('Sissa', 'Emilia-Romagna'),
('San Benedetto Val di Sambro', 'Emilia-Romagna'),
('Appignano', 'Marche'),
('Bormio', 'Lombardy'),
('Torricella', 'Puglia'),
('Piancastagnaio', 'Tuscany'),
('San Calogero', 'Calabria'),
('Carpiano', 'Lombardy'),
('Orgosolo', 'Sardegna'),
('Ussana', 'Sardegna'),
('Olmedo', 'Sardegna'),
('Rovetta', 'Lombardy'),
('Canale Monterano', 'Lazio'),
('Fossalta di Piave', 'Veneto'),
('Vertemate', 'Lombardy'),
('Bolognetta', 'Sicilia'),
('Sabbioneta', 'Lombardy'),
('Altavilla Irpina', 'Campania'),
('Francavilla in Sinni', 'Basilicata'),
('Stanghella', 'Veneto'),
('Solbiate Arno', 'Lombardy'),
('Nusco', 'Campania'),
('Berbenno di Valtellina', 'Lombardy'),
('Santa Maria Nuova', 'Marche'),
('Gorgo al Monticano', 'Veneto'),
('Pofi', 'Lazio'),
('Boffalora sopra Ticino', 'Lombardy'),
('Fumane', 'Veneto'),
('Mazzè', 'Piedmont'),
('Montopoli in Sabina', 'Lazio'),
('Cursi', 'Puglia'),
('Travedona', 'Lombardy'),
('Casirate d’Adda', 'Lombardy'),
('Santa Sofia', 'Emilia-Romagna'),
('Mògoro', 'Sardegna'),
('Garda', 'Veneto'),
('Sondalo', 'Lombardy'),
('Lallio', 'Lombardy'),
('Sori', 'Liguria'),
('Stigliano', 'Basilicata'),
('Brembilla', 'Lombardy'),
('Roccalumera', 'Sicilia'),
('San Pietro a Maida', 'Calabria'),
('Offlaga', 'Lombardy'),
('Moretta', 'Piedmont'),
('Castelmassa', 'Mantova'),
('Carpino', 'Puglia'),
('Moiano', 'Campania'),
('Limatola', 'Campania'),
('Tollo', 'Abruzzo'),
('Avio', 'Trentino-Alto Adige'),
('Liscate', 'Lombardy'),
('Agordo', 'Veneto'),
('Covo', 'Lombardy'),
('Pomarico', 'Basilicata'),
('Casirile', 'Lombardy'),
('Calangianus', 'Sardegna'),
('Sale', 'Piedmont'),
('Sant’Eufemia d’Aspromonte', 'Calabria'),
('Sirolo', 'Marche'),
('Capalbio', 'Tuscany'),
('Isorella', 'Lombardy'),
('San Salvatore Telesino', 'Campania'),
('Cavalese', 'Trentino-Alto Adige'),
('Sant’Angelo in Vado', 'Marche'),
('Premariacco', 'Friuli-Venezia Giulia'),
('Pietragalla', 'Basilicata'),
('Quarona', 'Piedmont'),
('Rolo', 'Emilia-Romagna'),
('Allumiere', 'Lazio'),
('Sogliano Cavour', 'Puglia'),
('Medole', 'Lombardy'),
('Pescina', 'Abruzzo'),
('Arnesano', 'Puglia'),
('Ballabio', 'Lombardy'),
('Ripa Teatina', 'Abruzzo'),
('Norma', 'Lazio'),
('Talmassons', 'Friuli-Venezia Giulia'),
('Villar Perosa', 'Piedmont'),
('Vasanello', 'Lazio'),
('Capoliveri', 'Tuscany'),
('Sardara', 'Sardegna'),
('Saluggia', 'Piedmont'),
('Cusano Mutri', 'Campania'),
('Lasa', 'Trentino-Alto Adige'),
('Civezzano', 'Trentino-Alto Adige'),
('Collesano', 'Sicilia'),
('Cappelle sul Tavo', 'Abruzzo'),
('Gibellina', 'Sicilia'),
('Marsico Nuovo', 'Basilicata'),
('Sanguinetto', 'Veneto'),
('Buttrio', 'Friuli-Venezia Giulia'),
('Carpineti', 'Emilia-Romagna'),
('Aiello del Sabato', 'Campania'),
('Casazza', 'Lombardy'),
('Bari Sardo', 'Sardegna'),
('Cesiomaggiore', 'Veneto'),
('Venetico', 'Sicilia'),
('Fiesso Umbertiano', 'Emilia-Romagna'),
('Castrocielo', 'Lazio'),
('Lugagnano Val d’Arda', 'Emilia-Romagna'),
('Vicovaro', 'Lazio'),
('Piedimonte Etneo', 'Sicilia'),
('Occhieppo Inferiore', 'Piedmont'),
('Brentonico', 'Trentino-Alto Adige'),
('Lattarico', 'Calabria'),
('Nuvolento', 'Lombardy'),
('Rosciano', 'Abruzzo'),
('Bolsena', 'Lazio'),
('Sant’Omobono Imagna', 'Lombardy'),
('Vescovato', 'Lombardy'),
('Annone Veneto', 'Veneto'),
('Vermezzo', 'Lombardy'),
('Palomonte', 'Campania'),
('Falerna', 'Calabria'),
('Tertenìa', 'Sardegna'),
('Caltavuturo', 'Sicilia'),
('Saponara Villafranca', 'Sicilia'),
('Castrignano de’ Greci', 'Puglia'),
('Piraino', 'Sicilia'),
('Moliterno', 'Basilicata'),
('Positano', 'Campania'),
('Santo Stefano Belbo', 'Piedmont'),
('Guiglia', 'Emilia-Romagna'),
('San Genesio ed Uniti', 'Lombardy'),
('San Benedetto de’ Marsi', 'Abruzzo'),
('Polesella', 'Veneto'),
('Arborea', 'Sardegna'),
('Sabbio Chiese', 'Lombardy'),
('Mathi', 'Piedmont'),
('Giano dell’Umbria', 'Umbria'),
('Casalbuttano', 'Lombardy'),
('Fonni', 'Sardegna'),
('Romagnano Sesia', 'Piedmont'),
('San Lorenzo di Sebato', 'Trentino-Alto Adige'),
('Contigliano', 'Lazio'),
('Scarlino', 'Tuscany'),
('Paduli', 'Campania'),
('San Martino di Venezze', 'Veneto'),
('Orsago', 'Veneto'),
('Serracapriola', 'Puglia'),
('Cittiglio', 'Lombardy'),
('Tiriolo', 'Calabria'),
('Pratola Serra', 'Campania'),
('Agnadello', 'Lombardy'),
('Pavone Canavese', 'Piedmont'),
('Trana', 'Piedmont'),
('Paderno d’Adda', 'Lombardy'),
('Cessalto', 'Veneto'),
('Francavilla di Sicilia', 'Sicilia'),
('Pernumia', 'Veneto'),
('Cerreto Sannita', 'Campania'),
('Casole d’Elsa', 'Tuscany'),
('Bagolino', 'Lombardy'),
('Buddusò', 'Sardegna'),
('Casola di Napoli', 'Campania'),
('Dovera', 'Lombardy'),
('Platì', 'Calabria'),
('Montemesola', 'Puglia'),
('Fagnano Castello', 'Calabria'),
('Battaglia Terme', 'Veneto'),
('Roncà', 'Veneto'),
('Cavriana', 'Lombardy'),
('Villa Lagarina', 'Trentino-Alto Adige'),
('Orsogna', 'Abruzzo'),
('Oriolo Romano', 'Lazio'),
('Maletto', 'Sicilia'),
('Lograto', 'Lombardy'),
('Bisaccia', 'Campania'),
('Follina', 'Veneto'),
('Petacciato', 'Molise'),
('Manta', 'Piedmont'),
('Scoppito', 'Abruzzo'),
('Salizzole', 'Veneto'),
('Esperia', 'Lazio'),
('Mongrando', 'Piedmont'),
('Aquaviva Picena', 'Marche'),
('Tromello', 'Lombardy'),
('Corchiano', 'Lazio'),
('Bienno', 'Lombardy'),
('Pieve di Cadore', 'Veneto'),
('Piobesi Torinese', 'Piedmont'),
('Sangano', 'Piedmont'),
('Fara Vicentino', 'Veneto'),
('Solopaca', 'Campania'),
('Pompiano', 'Lombardy'),
('Gaglianico', 'Piedmont'),
('Lestizza', 'Friuli-Venezia Giulia'),
('Castagnole Lanze', 'Piedmont'),
('Serra de’ Conti', 'Marche'),
('Tuoro sul Trasimeno', 'Umbria'),
('Castiòns di Strada', 'Friuli-Venezia Giulia'),
('Sedegliano', 'Friuli-Venezia Giulia'),
('Prignano sulla Secchia', 'Emilia-Romagna'),
('Numana', 'Marche'),
('San Giovanni a Piro', 'Campania'),
('Oppido Lucano', 'Basilicata'),
('Canossa', 'Emilia-Romagna'),
('Verolavecchia', 'Lombardy'),
('Civitella di Romagna', 'Emilia-Romagna'),
('Pitigliano', 'Tuscany'),
('Carpignano Salentino', 'Puglia'),
('Castagnaro', 'Veneto'),
('Grumolo delle Abbadesse', 'Veneto'),
('Bellagio', 'Lombardy'),
('Colonnella', 'Abruzzo'),
('Saracena', 'Calabria'),
('Goro', 'Emilia-Romagna'),
('Massa Martana', 'Umbria'),
('Pontelongo', 'Veneto'),
('Porto Azzurro', 'Tuscany'),
('Oliveto Citra', 'Campania'),
('Carasco', 'Liguria'),
('Caldonazzo', 'Trentino-Alto Adige'),
('Gallicano', 'Tuscany'),
('Taino', 'Lombardy'),
('Mondavio', 'Marche'),
('Parcines', 'Trentino-Alto Adige'),
('Deliceto', 'Puglia'),
('Chiarano', 'Veneto'),
('Cercemaggiore', 'Molise'),
('Villasimìus', 'Sardegna'),
('Romàns d’Isonzo', 'Friuli-Venezia Giulia'),
('Dubino', 'Lombardy'),
('San Luca', 'Calabria'),
('Vaiano Cremasco', 'Lombardy'),
('Miradolo Terme', 'Lombardy'),
('Spotorno', 'Liguria'),
('Cerreto d’Esi', 'Marche'),
('Ciminna', 'Sicilia'),
('Colli del Tronto', 'Marche'),
('Masone', 'Liguria'),
('Voghenza', 'Emilia-Romagna'),
('Magliano Sabina', 'Lazio'),
('Monghidoro', 'Emilia-Romagna'),
('Vidor', 'Veneto'),
('Malcesine', 'Veneto'),
('Tufino', 'Campania'),
('Spongano', 'Puglia'),
('Riccò del Golfo di Spezia', 'Liguria'),
('Fauglia', 'Tuscany'),
('Nizza di Sicilia', 'Sicilia'),
('Cattolica Eraclea', 'Sicilia'),
('Frigento', 'Campania'),
('Paderno Franciacorta', 'Lombardy'),
('Baldissero Torinese', 'Piedmont'),
('Villa Minozzo', 'Emilia-Romagna'),
('Scafa', 'Abruzzo'),
('Rodi Garganico', 'Puglia'),
('Rotondi', 'Campania'),
('Cavaglià', 'Piedmont'),
('Chiusa di Pesio', 'Piedmont'),
('Squillace', 'Calabria'),
('Sant’Oreste', 'Lazio'),
('San Pietro in Guarano', 'Calabria'),
('Bene Vagienna', 'Piedmont'),
('Nogarole Rocca', 'Veneto'),
('Montaione', 'Tuscany'),
('Faicchio', 'Campania'),
('Tione di Trento', 'Trentino-Alto Adige'),
('Artogne', 'Lombardy'),
('San Vito', 'Sardegna'),
('Magliano de’ Marsi', 'Abruzzo'),
('Migliarino', 'Emilia-Romagna'),
('Falciano Selice', 'Campania'),
('Lascari', 'Sicilia'),
('Pradamano', 'Friuli-Venezia Giulia'),
('Bagnoli di Sopra', 'Veneto'),
('Molteno', 'Lombardy'),
('Bagnoregio', 'Lazio'),
('Mignanego', 'Liguria'),
('Neviano degli Arduini', 'Emilia-Romagna'),
('Limbadi', 'Calabria'),
('Pontecurone', 'Piedmont'),
('Minervino di Lecce', 'Puglia'),
('Baunei', 'Sardegna'),
('Airasca', 'Piedmont'),
('Borgofranco d’Ivrea', 'Piedmont'),
('Bivona', 'Sicilia'),
('Morro d’Oro', 'Abruzzo'),
('Pont-Saint-Martin', 'Valle d’Aosta'),
('Diano d’Alba', 'Piedmont'),
('San Fratello', 'Sicilia'),
('Montecalvo Irpino', 'Campania'),
('Colliano', 'Campania'),
('Bobbio', 'Emilia-Romagna'),
('Asso', 'Lombardy'),
('Montelupone', 'Marche'),
('Piegaro', 'Umbria'),
('Ghemme', 'Piedmont'),
('Pozzonovo', 'Veneto'),
('Amandola', 'Marche'),
('Bosco Chiesanuova', 'Veneto'),
('Albuzzano', 'Lombardy'),
('Caltabellotta', 'Sicilia'),
('Massa Fiscaglia', 'Emilia-Romagna'),
('Pozzolengo', 'Lombardy'),
('Sergnano', 'Lombardy'),
('Lucignano', 'Tuscany'),
('Gioia Sannitica', 'Campania'),
('Ceregnano', 'Veneto'),
('San Leonardo in Passiria', 'Trentino-Alto Adige'),
('Brancaleone Superiore', 'Calabria'),
('Villamassargia', 'Sardegna'),
('Portovenere', 'Liguria'),
('Ruoti', 'Basilicata'),
('San Vito di Leguzzano', 'Veneto'),
('Magliano in Toscana', 'Tuscany'),
('San Pietro in Lama', 'Puglia'),
('Gagliano Castelferrato', 'Sicilia'),
('Aci Bonaccorsi', 'Sicilia'),
('Miggiano', 'Puglia'),
('Alia', 'Sicilia'),
('Castelplanio', 'Marche'),
('Monasterace', 'Calabria'),
('Pravisdomini', 'Friuli-Venezia Giulia'),
('Valledolmo', 'Sicilia'),
('Faggiano', 'Puglia'),
('Marano Marchesato', 'Calabria'),
('Badia', 'Trentino-Alto Adige'),
('Narzole', 'Piedmont'),
('Tribiano', 'Lombardy'),
('Laterina', 'Tuscany'),
('Ardesio', 'Lombardy'),
('Bagnário Arsa', 'Friuli-Venezia Giulia'),
('Tronzano Vercellese', 'Piedmont'),
('Bressana Bottarone', 'Lombardy'),
('Satriano', 'Calabria'),
('Bovolenta', 'Veneto'),
('Mairano', 'Lombardy'),
('San Paolo Bel Sito', 'Campania'),
('Alanno', 'Abruzzo'),
('Zapponeta', 'Puglia'),
('Citerna', 'Umbria'),
('Neive', 'Piedmont'),
('Beinette', 'Piedmont'),
('Endine Gaiano', 'Lombardy'),
('Casal Fiumanese', 'Emilia-Romagna'),
('Casale Corte Cerro', 'Piedmont'),
('Loreo', 'Veneto'),
('Montefano', 'Marche'),
('Pescaglia', 'Tuscany'),
('Piadena', 'Lombardy'),
('Balsorano Nuovo', 'Abruzzo'),
('Cengio', 'Liguria'),
('Altidona', 'Marche'),
('Collazzone', 'Umbria'),
('Gesualdo', 'Campania'),
('Lauro', 'Campania'),
('San Demetrio Corone', 'Calabria'),
('Sassocorvaro', 'Marche'),
('Fornovo San Giovanni', 'Lombardy'),
('Ornavasso', 'Piedmont'),
('Montalto Dora', 'Piedmont'),
('Caposele', 'Campania'),
('Lusia', 'Veneto'),
('Bosisio Parini', 'Lombardy'),
('Cimadolmo', 'Veneto'),
('Castione della Presolana', 'Lombardy'),
('Castel di Casio', 'Emilia-Romagna'),
('Dosolo', 'Mantova'),
('Sarsina', 'Emilia-Romagna'),
('Castelliri', 'Lazio'),
('Sicignano degli Alburni', 'Campania'),
('Torrecuso', 'Campania'),
('Valfabbrica', 'Umbria'),
('Cianciana', 'Sicilia'),
('Roccamonfina', 'Campania'),
('San Felice del Benaco', 'Lombardy'),
('Ripalta Cremasca', 'Lombardy'),
('Roncofreddo', 'Emilia-Romagna'),
('Bonorva', 'Sardegna'),
('Santadi', 'Sardegna'),
('Remedello Sopra', 'Lombardy'),
('Vallelunga Pratameno', 'Sicilia'),
('Forno Canavese', 'Piedmont'),
('Dongo', 'Lombardy'),
('Gressan', 'Valle d’Aosta'),
('San Ginesio', 'Marche'),
('Monsano', 'Marche'),
('Carolei', 'Calabria'),
('Costa di Mezzate', 'Lombardy'),
('Roccabernarda', 'Calabria'),
('San Lorenzo del Vallo', 'Calabria'),
('Sale Marasino', 'Lombardy'),
('Ceppaloni', 'Campania'),
('Oulx', 'Piedmont'),
('Pontida', 'Lombardy'),
('Bedonia', 'Emilia-Romagna'),
('San Candido', 'Trentino-Alto Adige'),
('San Giusto Canavese', 'Piedmont'),
('Viggiano', 'Basilicata'),
('Dobbiaco', 'Trentino-Alto Adige'),
('Costigliole Saluzzo', 'Piedmont'),
('Vernate', 'Lombardy'),
('Viano', 'Emilia-Romagna'),
('Polverara', 'Veneto'),
('Grottazzolina', 'Marche'),
('Contursi', 'Campania'),
('Falerone', 'Marche'),
('Marene', 'Piedmont'),
('Vellezzo Bellini', 'Lombardy'),
('Maslianico', 'Lombardy'),
('Paterno', 'Basilicata'),
('Millesimo', 'Liguria'),
('Biandronno', 'Lombardy'),
('Rocca Imperiale', 'Calabria'),
('Montese', 'Emilia-Romagna'),
('Delianuova', 'Calabria'),
('Furci Siculo', 'Sicilia'),
('Sorano', 'Tuscany'),
('Vibonati', 'Campania'),
('Vinchiaturo', 'Molise'),
('Sperlonga', 'Lazio'),
('Ferrazzano', 'Molise'),
('San Vito Romano', 'Lazio'),
('Villafrati', 'Sicilia'),
('Pont Canavese', 'Piedmont'),
('Aquiléia', 'Friuli-Venezia Giulia'),
('Auronzo di Cadore', 'Veneto'),
('San Marco dei Cavoti', 'Campania'),
('Ospedaletti', 'Liguria'),
('Gimigliano', 'Calabria'),
('San Giovanni Incarico', 'Lazio'),
('Narcao', 'Sardegna'),
('Foglianise', 'Campania'),
('Blera', 'Lazio'),
('Castellana Sicula', 'Sicilia'),
('Montefalcione', 'Campania'),
('Miane', 'Veneto'),
('Scalenghe', 'Piedmont'),
('Gais', 'Trentino-Alto Adige'),
('Caronia', 'Sicilia'),
('Casamarciano', 'Campania'),
('Agna', 'Veneto'),
('Ardenno', 'Lombardy'),
('Baiso', 'Emilia-Romagna'),
('Oschiri', 'Sardegna'),
('Godiasco', 'Lombardy'),
('Bovino', 'Puglia'),
('Delebio', 'Lombardy'),
('Cogollo del Cengio', 'Veneto'),
('San Lorenzo in Campo', 'Marche'),
('Morolo', 'Lazio'),
('Corio', 'Piedmont'),
('Morciano di Leuca', 'Puglia'),
('Montemaggiore Belsito', 'Sicilia'),
('Castel Ritaldi', 'Umbria'),
('Petralia Soprana', 'Sicilia'),
('Polizzi Generosa', 'Sicilia'),
('Borgo Tossignano', 'Emilia-Romagna'),
('Brebbia', 'Lombardy'),
('Cinto Caomaggiore', 'Veneto'),
('Camporeale', 'Sicilia'),
('Santa Marina', 'Campania'),
('Cessaniti', 'Calabria'),
('Valle Mosso', 'Piedmont'),
('Sogliano al Rubicone', 'Emilia-Romagna'),
('Scerni', 'Abruzzo'),
('Bibbona', 'Tuscany'),
('Casnigo', 'Lombardy'),
('Stienta', 'Ferrara'),
('Sarnano', 'Marche'),
('Andorno Micca', 'Piedmont'),
('Mezzani', 'Emilia-Romagna'),
('Abbadia Lariana', 'Lombardy'),
('Gaggi', 'Sicilia'),
('Saint-Pierre', 'Valle d’Aosta'),
('San Biagio Platani', 'Sicilia'),
('Ro', 'Emilia-Romagna'),
('Perosa Argentina', 'Piedmont'),
('Volturara Irpina', 'Campania'),
('Antegnate', 'Lombardy'),
('Bellano', 'Lombardy'),
('Coazze', 'Piedmont'),
('San Michele di Ganzaria', 'Sicilia'),
('Manocalzati', 'Campania'),
('Castelnuovo Don Bosco', 'Piedmont'),
('Sesto ed Uniti', 'Lombardy'),
('Varzi', 'Lombardy'),
('Camposanto', 'Emilia-Romagna'),
('Casalmaiocco', 'Lombardy'),
('Tolve', 'Basilicata'),
('Fonzaso', 'Veneto'),
('Villagrande Strisaili', 'Sardegna'),
('Malonno', 'Lombardy'),
('Civitella Marittima', 'Tuscany'),
('Ostra Vetere', 'Marche'),
('Rocca d’Evandro', 'Campania'),
('Marone', 'Lombardy'),
('Marano Principato', 'Calabria'),
('Jerzu', 'Sardegna'),
('Marliana', 'Tuscany'),
('Frosolone', 'Molise'),
('Montecalvoli', 'Tuscany'),
('Corno di Rosazzo', 'Friuli-Venezia Giulia'),
('Valli del Pasubio', 'Veneto'),
('Moscufo', 'Abruzzo'),
('Forano', 'Lazio'),
('San Gillio', 'Piedmont'),
('Rovito', 'Calabria'),
('Zinasco', 'Lombardy'),
('Civitella Roveto', 'Abruzzo'),
('Bressanvido', 'Veneto'),
('Decollatura', 'Calabria'),
('Carlazzo', 'Lombardy'),
('Patrica', 'Lazio'),
('Folgaria', 'Trentino-Alto Adige'),
('Mignano Monte Lungo', 'Campania'),
('Bardonecchia', 'Piedmont'),
('Belfiore', 'Veneto'),
('San Michele all’Adige', 'Trentino-Alto Adige'),
('Polcenigo', 'Friuli-Venezia Giulia'),
('Arsiero', 'Veneto'),
('Marano di Valpolicella', 'Veneto'),
('Viguzzolo', 'Piedmont'),
('Cantagallo', 'Tuscany'),
('Serrara Fontana', 'Campania'),
('Scandriglia', 'Lazio'),
('Bagnoli Irpino', 'Campania'),
('Buonconvento', 'Tuscany'),
('Casella', 'Liguria'),
('Balangero', 'Piedmont'),
('Aldeno', 'Trentino-Alto Adige'),
('Maleo', 'Lombardy'),
('Garessio', 'Piedmont'),
('Castiglione di Sicilia', 'Sicilia'),
('Cerisano', 'Calabria'),
('Pergine Valdarno', 'Tuscany'),
('San Giorgio a Liri', 'Lazio'),
('Mazzano Romano', 'Lazio'),
('Maenza', 'Lazio'),
('Pieve Santo Stefano', 'Tuscany'),
('Sospirolo', 'Veneto'),
('Romanengo', 'Lombardy'),
('Fontanarosa', 'Campania'),
('Cascia', 'Umbria'),
('Montorso Vicentino', 'Veneto'),
('Bosconero', 'Piedmont'),
('Menaggio', 'Lombardy'),
('Serrastretta', 'Calabria'),
('Grotteria', 'Calabria'),
('Ripalimosani', 'Molise'),
('Suvereto', 'Tuscany'),
('Raddusa', 'Sicilia'),
('Scandale', 'Calabria'),
('Capizzi', 'Sicilia'),
('Rio di Pusteria', 'Trentino-Alto Adige'),
('San Leucio del Sannio', 'Campania'),
('Lozzo Atestino', 'Veneto'),
('Pietrelcina', 'Campania'),
('Castel Focognano', 'Tuscany'),
('Pastrengo', 'Veneto'),
('Nanto', 'Veneto'),
('Robassomero', 'Piedmont'),
('Monte Roberto', 'Marche'),
('Sant’Onofrio', 'Calabria'),
('Licodia Eubea', 'Sicilia'),
('Comunanza', 'Marche'),
('Baone', 'Veneto'),
('Caprino Bergamasco', 'Lombardy'),
('San Maurizio d’Opaglio', 'Piedmont'),
('Villanterio', 'Lombardy'),
('Contrada', 'Campania'),
('Saludecio', 'Emilia-Romagna'),
('Marradi', 'Tuscany'),
('Sarmede', 'Veneto'),
('Sospiro', 'Lombardy'),
('Bernate Ticino', 'Lombardy'),
('Castell’Umberto', 'Sicilia'),
('Torino di Sangro', 'Abruzzo'),
('Fogliano Redipúglia', 'Friuli-Venezia Giulia'),
('Volano', 'Trentino-Alto Adige'),
('Serrone', 'Lazio'),
('Pattada', 'Sardegna'),
('Villafranca d’Asti', 'Piedmont'),
('Casalincontrada', 'Abruzzo'),
('San Giorgio Morgeto', 'Calabria'),
('Torre de’ Passeri', 'Abruzzo'),
('San Genesio Atesino', 'Trentino-Alto Adige'),
('Pinzolo', 'Trentino-Alto Adige'),
('Orgiano', 'Veneto'),
('Prata di Principato Ultra', 'Campania'),
('Torri del Benaco', 'Veneto'),
('Sturno', 'Campania'),
('Soveria Mannelli', 'Calabria'),
('Crucoli', 'Calabria'),
('Tramutola', 'Basilicata'),
('San Pietro Viminario', 'Veneto'),
('Caselette', 'Piedmont'),
('Fluminimaggiore', 'Sardegna'),
('Canepina', 'Lazio'),
('Sanfrè', 'Piedmont'),
('Castronuovo di Sicilia', 'Sicilia'),
('Samughèo', 'Sardegna'),
('Santa Cesarea Terme', 'Puglia'),
('Serle', 'Lombardy'),
('Africo', 'Calabria'),
('Longobucco', 'Calabria'),
('Osilo', 'Sardegna'),
('Campofranco', 'Sicilia'),
('Caselle Lurani', 'Lombardy'),
('Stia', 'Tuscany'),
('Nissoria', 'Sicilia'),
('Sant’Angelo di Brolo', 'Sicilia'),
('Villa di Tirano', 'Lombardy'),
('Posada', 'Sardegna'),
('Badolato', 'Calabria'),
('Gazoldo degli Ippoliti', 'Lombardy'),
('Roccabianca', 'Emilia-Romagna'),
('Fregona', 'Veneto'),
('Moncalvo', 'Piedmont'),
('Pietravairano', 'Campania'),
('Diso', 'Puglia'),
('Giarratana', 'Sicilia'),
('Castiglione Cosentino', 'Calabria'),
('Lentiai', 'Veneto'),
('Misano di Gera d’Adda', 'Lombardy'),
('Mormanno', 'Calabria'),
('Cassine', 'Piedmont'),
('Monterosso Almo', 'Sicilia'),
('San Giorgio la Molara', 'Campania'),
('Prata Camportaccio', 'Lombardy'),
('Montevago', 'Sicilia'),
('Pollina', 'Sicilia'),
('Verbicaro', 'Calabria'),
('Fanano', 'Emilia-Romagna'),
('Fiumefreddo Bruzio', 'Calabria'),
('Flumeri', 'Campania'),
('Porto Ceresio', 'Lombardy'),
('Tesero', 'Trentino-Alto Adige'),
('Viggianello', 'Basilicata'),
('Pralboino', 'Lombardy'),
('Spigno Saturnia', 'Lazio'),
('Thiesi', 'Sardegna'),
('Rovagnate', 'Lombardy'),
('Dugenta', 'Campania'),
('Ostiano', 'Lombardy'),
('San Fele', 'Basilicata'),
('Vitulano', 'Campania'),
('San Polo dei Cavalieri', 'Lazio'),
('Sant’Agata sul Santerno', 'Emilia-Romagna'),
('Meduna di Livenza', 'Veneto'),
('Castrofilippo', 'Sicilia'),
('Villafalletto', 'Piedmont'),
('Cassacco', 'Friuli-Venezia Giulia'),
('Velturno', 'Trentino-Alto Adige'),
('Fontana Liri', 'Lazio'),
('Roncegno', 'Trentino-Alto Adige'),
('Comerio', 'Lombardy'),
('Castri di Lecce', 'Puglia'),
('Amendolara', 'Calabria'),
('Ruda', 'Friuli-Venezia Giulia'),
('Acquanegra sul Chiese', 'Lombardy'),
('Cerrione', 'Piedmont'),
('Palazzolo dello Stella', 'Friuli-Venezia Giulia'),
('Filiano', 'Basilicata'),
('Lettomanoppello', 'Abruzzo'),
('Campo Ligure', 'Liguria'),
('San Leo', 'Marche'),
('Valentano', 'Lazio'),
('Gemonio', 'Lombardy'),
('Riva Ligure', 'Liguria'),
('Mezzojuso', 'Sicilia'),
('Castel Viscardo', 'Umbria'),
('Montemaggiore al Metauro', 'Marche'),
('Artegna', 'Friuli-Venezia Giulia'),
('Faedis', 'Friuli-Venezia Giulia'),
('Trescore Cremasco', 'Lombardy'),
('Francavilla Marittima', 'Calabria'),
('Alessandria della Rocca', 'Sicilia'),
('Briga Novarese', 'Piedmont'),
('Osoppo', 'Friuli-Venezia Giulia'),
('Gargnano', 'Lombardy'),
('Sirignano', 'Campania'),
('Ragogna', 'Friuli-Venezia Giulia'),
('Borghi', 'Emilia-Romagna'),
('Grandate', 'Lombardy'),
('Castellina in Chianti', 'Tuscany'),
('Airuno', 'Lombardy'),
('Madignano', 'Lombardy'),
('Sarmato', 'Emilia-Romagna'),
('Torpè', 'Sardegna'),
('Terzo d’Aquiléia', 'Friuli-Venezia Giulia'),
('Ordona', 'Puglia'),
('Crecchio', 'Abruzzo'),
('Bellegra', 'Lazio'),
('Tiggiano', 'Puglia'),
('Monte di Malo', 'Veneto'),
('Chienes', 'Trentino-Alto Adige'),
('Iolanda di Savoia', 'Emilia-Romagna'),
('Turriaco', 'Friuli-Venezia Giulia'),
('Santa Vittoria d’Alba', 'Piedmont'),
('Letoianni', 'Sicilia'),
('Torviscosa', 'Friuli-Venezia Giulia'),
('Fabro', 'Umbria'),
('Uras', 'Sardegna'),
('Celico', 'Calabria'),
('Tusa', 'Sicilia'),
('San Piero Patti', 'Sicilia'),
('Gallese', 'Lazio'),
('Guarno', 'Calabria'),
('Castelnuovo Cilento', 'Campania'),
('Vercurago', 'Lombardy'),
('Pedaso', 'Marche'),
('Moriago della Battaglia', 'Veneto'),
('Sant’Arsenio', 'Campania'),
('Sciara', 'Sicilia'),
('Lamon', 'Veneto'),
('Monteviale', 'Veneto'),
('Saletto', 'Veneto'),
('Montemarano', 'Campania'),
('Bitti', 'Sardegna'),
('Bronzolo', 'Trentino-Alto Adige'),
('Moneglia', 'Liguria'),
('Sommariva Perno', 'Piedmont'),
('Scurcola Marsicana', 'Abruzzo'),
('Gruaro', 'Veneto'),
('Suno', 'Piedmont'),
('Morsano al Tagliamento', 'Friuli-Venezia Giulia'),
('Bonifati', 'Calabria'),
('Vietri di Potenza', 'Basilicata'),
('Burcèi', 'Sardegna'),
('Acquasanta Terme', 'Marche'),
('Carlino', 'Friuli-Venezia Giulia'),
('Candela', 'Puglia'),
('Traona', 'Lombardy'),
('Petriano', 'Marche'),
('La Morra', 'Piedmont'),
('Pozzoleone', 'Veneto'),
('Courmayeur', 'Valle d’Aosta'),
('Cividate Camuno', 'Lombardy'),
('Falcone', 'Sicilia'),
('Pennabilli', 'Marche'),
('San Pier Niceto', 'Sicilia'),
('Orsenigo', 'Lombardy'),
('Raiano', 'Abruzzo'),
('Mandatoriccio', 'Calabria'),
('Piasco', 'Piedmont'),
('Chiusa Sclafani', 'Sicilia'),
('Pavone del Mella', 'Lombardy'),
('Biccari', 'Puglia'),
('Bettola', 'Emilia-Romagna'),
('Gaiole in Chianti', 'Tuscany'),
('Trevenzuolo', 'Veneto'),
('Montecalvo in Foglia', 'Marche'),
('Berlingo', 'Lombardy'),
('Amorosi', 'Campania'),
('Berchidda', 'Sardegna'),
('Botrugno', 'Puglia'),
('Lessona', 'Piedmont'),
('Salandra', 'Basilicata'),
('Serra San Quirico', 'Marche'),
('Arrone', 'Umbria'),
('Fossato di Vico', 'Umbria'),
('Sant’Anna Arresi', 'Sardegna'),
('Castignano', 'Marche'),
('Cordovado', 'Friuli-Venezia Giulia'),
('Zandobbio', 'Lombardy'),
('Mammola', 'Calabria'),
('Rivello', 'Basilicata'),
('Petralia Sottana', 'Sicilia'),
('Golasecca', 'Piedmont'),
('Barile', 'Basilicata'),
('Occhieppo Superiore', 'Piedmont'),
('Valle di Maddaloni', 'Campania'),
('Varmo', 'Friuli-Venezia Giulia'),
('Paesana', 'Piedmont'),
('Monforte San Giorgio', 'Sicilia'),
('Pabillonis', 'Sardegna'),
('Formignana', 'Emilia-Romagna'),
('Acerno', 'Campania'),
('Seminara', 'Calabria'),
('Nimis', 'Friuli-Venezia Giulia'),
('Trecenta', 'Veneto'),
('Marlengo', 'Trentino-Alto Adige'),
('Bornasco', 'Lombardy'),
('Castell’Alfero', 'Piedmont'),
('Mele', 'Liguria'),
('Lama Mocogno', 'Emilia-Romagna'),
('Nulvi', 'Sardegna'),
('Gissi', 'Abruzzo'),
('Orsara di Puglia', 'Puglia'),
('Villanova d’Albenga', 'Liguria'),
('Bargagli', 'Liguria'),
('Casaloldo', 'Lombardy'),
('Bereguardo', 'Lombardy'),
('Poggio Imperiale', 'Puglia'),
('Brembio', 'Lombardy'),
('Canaro', 'Veneto'),
('Rossiglione', 'Liguria'),
('Gussola', 'Lombardy'),
('Noli', 'Liguria'),
('Abbasanta', 'Sardegna'),
('Montesano Salentino', 'Puglia'),
('Baschi', 'Umbria'),
('Montecorice', 'Campania'),
('Santa Maria la Fossa', 'Campania'),
('Guasila', 'Sardegna'),
('Fiano', 'Piedmont'),
('Cetona', 'Tuscany'),
('Porto Ercole', 'Tuscany'),
('Caggiano', 'Campania'),
('Laion', 'Trentino-Alto Adige'),
('Serdiana', 'Sardegna'),
('Pietra Montecorvino', 'Puglia'),
('San Mango Piemonte', 'Campania'),
('Pieve Porto Morone', 'Lombardy'),
('San Fili', 'Calabria'),
('Apollosa', 'Campania'),
('Castel San Niccolò', 'Tuscany'),
('Sandigliano', 'Piedmont'),
('Toirano', 'Liguria'),
('Casalvieri', 'Lazio'),
('Guardamiglio', 'Lombardy'),
('Vicari', 'Sicilia'),
('Besenello', 'Trentino-Alto Adige'),
('Villamar', 'Sardegna'),
('Vallata', 'Campania'),
('Romano Canavese', 'Piedmont'),
('San Cono', 'Sicilia'),
('Cantalice', 'Lazio'),
('Campodoro', 'Veneto'),
('Castelvenere', 'Campania'),
('Alice Castello', 'Piedmont'),
('Ururi', 'Molise'),
('Grotte di Castro', 'Lazio'),
('Sgurgola', 'Lazio'),
('Fontaneto d’Agogna', 'Piedmont'),
('Poggio Moiano', 'Lazio'),
('Genola', 'Piedmont'),
('Alvito', 'Lazio'),
('Cuglieri', 'Sardegna'),
('Roccavione', 'Piedmont'),
('San Quirico d’Orcia', 'Tuscany'),
('Merlara', 'Veneto'),
('Sinagra', 'Sicilia'),
('Verrès', 'Valle d’Aosta'),
('Gavoi', 'Sardegna'),
('Tocco da Casauria', 'Abruzzo'),
('Moena', 'Trentino-Alto Adige'),
('Cison di Valmarino', 'Veneto'),
('San Colombano Certenoli', 'Liguria'),
('Solferino', 'Lombardy'),
('Gardone Riviera', 'Lombardy'),
('San Nicolò d’Arcidano', 'Sardegna'),
('Burgio', 'Sicilia'),
('Schiavon', 'Veneto'),
('Pisciotta', 'Campania'),
('Casabona', 'Calabria'),
('Dervio', 'Lombardy'),
('Castel Sant’Elia', 'Lazio'),
('Varano de’ Melegari', 'Emilia-Romagna'),
('San Gregorio d’Ippona', 'Calabria'),
('Badia Calavena', 'Veneto'),
('Agliè', 'Piedmont'),
('Torricella Sicura', 'Abruzzo'),
('Selva', 'Trentino-Alto Adige'),
('Pianopoli', 'Calabria'),
('Baranello', 'Molise'),
('Fratta Polesine', 'Veneto'),
('Baragiano', 'Basilicata'),
('Trenta', 'Calabria'),
('Caravate', 'Lombardy'),
('Gravedona', 'Lombardy'),
('Ceresara', 'Lombardy'),
('Rivara', 'Piedmont'),
('Mereto di Tomba', 'Friuli-Venezia Giulia'),
('Villa Santa Lucia', 'Lazio'),
('Casola Valsenio', 'Emilia-Romagna'),
('Gerace', 'Calabria'),
('Rotondella', 'Basilicata'),
('Ausonia', 'Lazio'),
('Vallerano', 'Lazio'),
('Villaspeciosa', 'Sardegna'),
('Lurago Marinone', 'Lombardy'),
('Besano', 'Lombardy'),
('Vignolo', 'Piedmont'),
('Ternate', 'Lombardy'),
('Lusiana', 'Veneto'),
('Valfurva', 'Lombardy'),
('Bolotana', 'Sardegna'),
('Porpetto', 'Friuli-Venezia Giulia'),
('Urbisaglia', 'Marche'),
('Pozzomaggiore', 'Sardegna'),
('Dolcè', 'Veneto'),
('Vallecorsa', 'Lazio'),
('Ponte', 'Campania'),
('Stilo', 'Calabria'),
('San Gervasio Bresciano', 'Lombardy'),
('Budoia', 'Friuli-Venezia Giulia'),
('San Vittore del Lazio', 'Lazio'),
('San Giorgio Canavese', 'Piedmont'),
('Vestenanuova', 'Veneto'),
('Petronà', 'Calabria'),
('Sanza', 'Campania'),
('Santa Fiora', 'Tuscany'),
('Casole Bruzio', 'Calabria'),
('Benestare', 'Calabria'),
('San Lorenzo', 'Calabria'),
('Moricone', 'Lazio'),
('Poggio Nativo', 'Lazio'),
('Costa di Rovigo', 'Veneto'),
('Paularo', 'Friuli-Venezia Giulia'),
('Buonabitacolo', 'Campania'),
('Rivarolo Mantovano', 'Lombardy'),
('Camerata Picena', 'Marche'),
('Chiuro', 'Lombardy'),
('Pieve Vergonte', 'Piedmont'),
('Pellestrina', 'Veneto'),
('Pignataro Interamna', 'Lazio'),
('Caltignaga', 'Piedmont'),
('Cinigiano', 'Tuscany'),
('Pressana', 'Veneto'),
('Sant’Anna d’Alfaedo', 'Veneto'),
('Lago', 'Calabria'),
('Chiuppano', 'Veneto'),
('Santa Sofia d’Epiro', 'Calabria'),
('Luras', 'Sardegna'),
('Ziano Piacentino', 'Emilia-Romagna'),
('Nuraminis', 'Sardegna'),
('Bergantino', 'Veneto'),
('Mamoiada', 'Sardegna'),
('Corleto Perticara', 'Basilicata'),
('Corbara', 'Campania'),
('Donnaz', 'Valle d’Aosta'),
('Caltrano', 'Veneto'),
('Galati Mamertino', 'Sicilia'),
('Campodipietra', 'Molise'),
('Molochio', 'Calabria'),
('Galeata', 'Emilia-Romagna'),
('Santo Stefano di Cadore', 'Veneto'),
('Momo', 'Piedmont'),
('Avigliano', 'Umbria'),
('Carpignano Sesia', 'Piedmont'),
('Lungro', 'Calabria'),
('Sant’Elena', 'Veneto'),
('Montallegro', 'Sicilia'),
('Amatrice', 'Lazio'),
('Moruzzo', 'Friuli-Venezia Giulia'),
('Muzzana del Turgnano', 'Friuli-Venezia Giulia'),
('Montodine', 'Lombardy'),
('Antrodoco', 'Lazio'),
('Pieve Ligure', 'Liguria'),
('Cellino Attanasio', 'Abruzzo'),
('San Vero Milis', 'Sardegna');